### ISSUE TITLE
404 on all languages exept the default one. 

### ISSUE THREAD

**Issue by patricijo** [aralroca/next-translate#1005]
**What version of this package are you using?**
2.0.2 / next 13.2.4

**What operating system, Node.js, and npm version?**
v18.14.2

**What happened?**
Using the new APP directory
When switching to a route other than the default language I get a 404 error. ("/en" works "/es" does not)

Also I dont see any compiling of the other languages in the console like:
next-translate - compiled page: / - locale: en - namespaces: common, home - used loader: force-dynamic (server page)

I recreatet the bug on a fresh next installation: https://codesandbox.io/p/github/patricijo/next-translate-test/master

**Comment by aralroca** [comment]
Is problem-related to the middleware, add this line:

```diff
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import i18n from "./i18n";

export function middleware(request: NextRequest) {
  const locale = request.nextUrl.locale || i18n.defaultLocale;
  request.nextUrl.searchParams.set("lang", locale);
+  request.nextUrl.href = request.nextUrl.href.replace(`/${locale}`, "");
  return NextResponse.rewrite(request.nextUrl);
}
```

Already solved here: https://github.com/aralroca/next-translate/issues/993

We updated the middleware from the example to the correct one.
