### ISSUE TITLE
I get lang params is undefined in nextjs 13 App folder

### ISSUE THREAD

**Issue by SinyorT** [aralroca/next-translate#1007]
**What version of this package are you using?**
2.0.2
**What operating system, Node.js, and npm version?**
v16.16.0
**What happened?**
I get lang params is undefined in Layout when i changed lang
**What did you expect to happen?**
I must get current language which i saw in url

**Comment by aralroca** [comment]
In the Next.js [documentation](https://beta.nextjs.org/docs/api-reference/file-conventions/layout#good-to-know) about `layout.js`:

> Unlike [Pages](https://beta.nextjs.org/docs/api-reference/file-conventions/page), Layout components do not receive the searchParams prop. This is because a shared layout is [not re-rendered during navigation](https://beta.nextjs.org/docs/routing/fundamentals#partial-renderingmd) which could lead to stale searchParams between navigations.
>
> Detailed explanation
When using client-side navigation, Next.js automatically only renders the part of the page below the common layout between two routes.
>
>For example, in the following directory structure, dashboard/layout.tsx is the common layout for both /dashboard and /dashboard/settings:

>```
>app
>└── dashboard
>    ├── layout.tsx
>    ├── page.tsx
>    └── settings
>        └── page.tsx
>```
>
>When navigating from /dashboard to /dashboard/settings, dashboard/settings/page.tsx will be rendered on the server because it the segment that changed, while dashboard/layout.tsx will not be re-rendered because it is a common layout between the two routes.
>
>This performance optimization allows navigation between pages that share a layout to be quicker as only the data fetching and rendering for the page has to run, instead of the entire route that could include shared layouts that fetch their own data.
>
>Because dashboard/layout.tsx doesn't re-render, reading a searchParams prop in the layout Server Component would become stale when navigating.
>
>Instead, use the Page [searchParams](https://beta.nextjs.org/docs/api-reference/file-conventions/page) prop or the [useSearchParams](https://beta.nextjs.org/docs/api-reference/use-search-params) hook in a Client Component, which is re-rendered on the client with the latest searchParams.

In [2.0.0](https://github.com/aralroca/next-translate/releases/tag/2.0.0) we improved the Next.js +13 appDir support, but it is currently implemented only for **pages** and **components**.

We are going to work in 2.1 to support also:

- `layout.js`
- `template.js`
- `error.js`
- `loading.js` 
- `not-found.js`

Meanwhile, as a workaround, you can use `"use client"` and `useSearchParams`:

```js
"use client"
import { useSearchParams } from 'next/navigation';

export default function Layout({ children }) {
 const searchParams = useSearchParams()
 const lang = searchParams.get('lang')
  return (
    <html lang={lang}>
      <head />
      <body>{children}</body>
    </html>
  );
}
```

And if you need the `t` function inside to do some translations, as a workaround you can use `transCore`:

```js
import transCore from 'next-translate/transCore'
import nextTranslateConfig from '../i18n'
// ...

const t = transCore({
  config: nextTranslateConfig,
  allNamespaces: { common: await nextTranslateConfig.loadLocaleFrom(lang, 'common') },
  pluralRules:  new Intl.PluralRules(en),
  lang,
});

t("common:title"); 
```
