### ISSUE TITLE
is it fast with many locales files?

### ISSUE THREAD

**Issue by fgvlasov** [aralroca/next-translate#1010]
**What version of this package are you using?**
We use next-translate v1.6.0" with Next v12.1.6

Is your library fast and responsive when we have hundred of pages rules?

```
module.exports = {
  locales: ["en", "fr"],
  defaultLocale: "en",
  pages: {
    "*": ["common"],
    "/site/settings/*": ["site/settings"],
    "/site/account/*": ["site/account"],
    "/applicant/settings/*": ["applicant/settings"],
    "/applicant/account/*": ["applicant/account"],

and HUNDREDS more here...
  },
};
```

in component we will use const { t } = useTranslation(); construction. 
It will work and insert json translation automatically for page like /applicant/settings/profile/personal ?

**Comment by aralroca** [comment]
Yes, because is downloading only the namespaces the page needs. If is already downloaded is not going to download it again during navigation.

Also, you can use regex with `rgx:` prefix, take a look at this example:

`'rgx:^/more-examples': ['more-examples'],`

https://github.com/aralroca/next-translate/blob/master/examples/complex/i18n.js#L10

**Comment by fgvlasov** [comment]
> Yes, because is downloading only the namespaces the page needs. If is already downloaded is not going to download it again during navigation.
> 
> Also, you can use regex with `rgx:` prefix, take a look at this example:
> 
> `'rgx:^/more-examples': ['more-examples'],`
> 
> https://github.com/aralroca/next-translate/blob/master/examples/complex/i18n.js#L10

I made an example, but it does not work. On page /site/settings it doesn`t get special title, which is described in i18n.json
"/site/settings": ["sites/settings/siteSettingsTranslations"]

My rep: https://github.com/fgvlasov/ex-transl

**Comment by aralroca** [comment]
The namespace should be without the `/`.  `"/site/settings": ["sites", "settings", "siteSettingsTranslations"]`.

Or:

```
module.exports = {
  locales: ["en", "fr"],
  defaultLocale: "en",
  pages: {
    "*": ["common"],
    "rgx:^/site/": ["site"],
    "rgx:^/applicant/": ["applicant"],
    "rgx:^/(site|applicant)/settings/": ["settings"],
    "rgx:^/(site|applicant)/account/": ["account"],

and HUNDREDS more here...
  },
};

```

**Comment by fgvlasov** [comment]
> The namespace should be without the `/`. `"/site/settings": ["sites", "settings", "siteSettingsTranslations"]`.
> 
> Or:
> 
> ```
> module.exports = {
>   locales: ["en", "fr"],
>   defaultLocale: "en",
>   pages: {
>     "*": ["common"],
>     "rgx:^/site/": ["site"],
>     "rgx:^/applicant/": ["applicant"],
>     "rgx:^/(site|applicant)/settings/": ["settings"],
>     "rgx:^/(site|applicant)/account/": ["account"],
> 
> and HUNDREDS more here...
>   },
> };
> ```

Why in component I can`t use clean const { t } = useTranslation() ???
but only const { t } = useTranslation("siteSettingsTranslations")
I thought we don`t need to implement namespace if it is described for this page in i18n.json file

**Comment by aralroca** [comment]
By default the support is in one level only:

`locales/<lang>/<namespace>.json`

So:

`locales/en/siteSettingsTranslations.json`

If you need a different structure you need to overwrite the `loadLocaleFrom` config field.

Please reads the docs.

**Comment by fgvlasov** [comment]
> By default the support is in one level only:
> 
> `locales/<lang>/<namespace>.json`
> 
> So:
> 
> `locales/en/siteSettingsTranslations.json`
> 
> If you need a different structure you need to overwrite the `loadLocaleFrom` config field.
> 
> Please reads the docs.

Can you write for us  code which will implement this task?
And we want to use only clean const { t } = useTranslation()
which will take translation file from folders inside language folders ? which would be similar to pages folder. Can you?

pages/site/settings/index.js component will see locales/en/site/settings/siteSettings.json 

We have very big application, we can not use 100 translation files inside lang folder in one level.

And it would be good that if translation is not found in this file then it will find in common file.

We can pay for your work in CAD or USD.
