### ISSUE TITLE
Type 'TranslateValue' is not assignable to type 'ReactNode'

### ISSUE THREAD

**Issue by andrewdoro** [aralroca/next-translate#1012]
**What version of this package are you using?**
2.0.3
**What operating system, Node.js, and npm version?**
Node 16, pnpm
**What happened?**

After #1011  TS complains when I pass the `t` function as children
<img width="807" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/17547035/227314193-08fcb7ce-6e57-4c4a-b6ad-958231883399.png">

You can fix the error by putting string as a generic, but I don't think that this should be a desired behavirour.

`
 {t<string>('translate.key')}
`

**Comment by jackylo-hc** [comment]
yes I think so, would there a fix soon?

**Comment by aralroca** [comment]
Probably this bug is introduced by this PR https://github.com/aralroca/next-translate/pull/931/  CC: @SimplyComplexable

**Comment by SimplyComplexable** [comment]
I'll take a look at this right now.

**Comment by aralroca** [comment]
Thanks @SimplyComplexable ! I released 2.0.4 with your change
