### ISSUE TITLE
Error: Cannot read properties of undefined (reading '_context')

### ISSUE THREAD

**Issue by benjick** [aralroca/next-translate#1019]
**What version of this package are you using?**
2.0.4

**What operating system, Node.js, and npm version?**
I'm running OSX
```
node -v
v18.7.0
npm -v
8.15.0
```

**What happened?**
I'm trying to migrate to use the `app`-directory. I've created this minimal page to try it out:

```tsx
import { CarDatabase } from "src/CarDatabase";
import useTranslation from "next-translate/useTranslation";

async function getCars() {
  const cars = await CarDatabase.findAllCars(12);
  return cars;
}

export default async function Page() {
  const cars = await getCars();
  const { t, lang } = useTranslation("common");
  return <p>Foo bar</p>;
}
```

But I'm getting the following error:

> Error: Cannot read properties of undefined (reading '_context')

**What did you expect to happen?**

I expected it to not throw

**Are you willing to submit a pull request to fix this bug?**

I'm not sure what the error is

**Comment by aralroca** [comment]
Try next-translate-plugin 2.0.4-canary.1

**Comment by benjick** [comment]
Hey! Thank you, I tried `2.0.5-canary.1` and it worked fine!
