### ISSUE TITLE
Storybook dynamic language change

### ISSUE THREAD

**Issue by CemYil03** [aralroca/next-translate#1036]
It would be amazing to have support for dynamically changing the language inside Storybook.

In the [storybook documentation](https://storybook.js.org/blog/internationalize-components-with-storybook) is a gif demonstrating how I would imagine it:

![GIF](https://storybookblog.ghost.io/content/images/2022/09/finished-switcher.gif)

**Comment by aralroca** [comment]
It's already possible, however, you need to add a decorator with `I18nProvider` https://github.com/aralroca/next-translate#i18nprovider at the top level. https://github.com/aralroca/next-translate/issues/210#issuecomment-665916895

**Comment by CemYil03** [comment]
But this only seems to provide a single language for the stories. With this issue primarily meant the ability to dynamically change the language with i.e. a dropdown.
