### ISSUE TITLE
getT: Cannot read properties of undefined (reading 'loadLocaleFrom')

### ISSUE THREAD

**Issue by Ayterx** [aralroca/next-translate#1038]
**What version of this package are you using?**
2.0.5

**What operating system, Node.js, and npm version?**
windows 11
18.13.0
8.19.3

**What happened?**
bug with getT

sometimes when requesting `/api/hello` it errors and the next request will resolve and sometimes it never works.

error: Error [TypeError]: Cannot read properties of undefined (reading 'loadLocaleFrom')

repo: https://github.com/Ayterx/next-translate-bug
video: https://youtu.be/J19bYSTk-c0

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**
no

**Comment by CDFN** [comment]
Having the same error. However, it happens to me only while deploying to Vercel. On my local machine it works just fine.

**Comment by CDFN** [comment]
Looks like my issue is related to #484. Possibly yours too?

**Comment by Ayterx** [comment]
@CDFN it happens in my machine

This is a strange issue that appeared recently. This problem occurred about a month ago on my side, and still, I don't know what caused it. I tried downgrading next-translate and next.js to different versions, but no hope.
