### ISSUE TITLE
TransText strips out new lines

### ISSUE THREAD

**Issue by MonstraG** [aralroca/next-translate#1047]
**What version of this package are you using?**
	"next-translate": "^2.0.5",

**What operating system, Node.js, and npm version?**
n/a

**What happened?**
TransText removes all my carefully placed `/n`s.

**What did you expect to happen?**
It doesn't.

**Are you willing to submit a pull request to fix this bug?**
Yea.

Issue comes from first line in `formatElements`, it's quite easy to fix.

Is there a particular reason it does that?

**Comment by MonstraG** [comment]
While looking at the line stripping I realized that html element matching regex might be incorrect also - self-closing portion is OR-ed with closing tag not with the entire thing, and having attributes or spaces in the tag will break it to.

Something like this `/(<(\w+)(.*?)>(.*?)<\/\2>|<(\w+)\/>)/` MIGHT work better.

**Comment by aralroca** [comment]
Instead of adding `/n` inside the text, you need to use **HTML tags**, in the same way that is not possible to use `/n` inside a paragraph: `<p>This is\n not working</p>`:

Instead of do:

```js
const text = '<This is some paragraph\nThis is another one'
// ...
<TransText text={listItem} />
  ```

You need to do this:

```js
const text = '<first>This is some paragraph</first><second>This is another one</second>'
// ...
<TransText
  text={listItem}
  components={{
    first: <p />,
    second: <p className="someclass" />
  }}
/>
  ```

**Comment by MonstraG** [comment]
I tried it with `<br />`, but this:
```
const text = '<p>This is some paragraph<br />This is another one</p>'
// ...
<TransText
  text={text}
  components={{
    p: <p />,
    br: <br />
  }}
/>
```
didn't work.

(I need to preserve a difference between line-break and new paragraph)

**Comment by aralroca** [comment]
Autoclosing tags are not supported, you need to use `<br></br>`:

```js
const text = '<p>This is some paragraph<br></br>This is another one</p>'
// ...
<TransText
  text={text}
  components={{
    p: <p />,
    br: <br />
  }}
/>
```

**Comment by aralroca** [comment]
@MonstraG good point, you are right. Looks that is supported, but is not working fine:


<img width="353" alt="Screenshot 2023-05-19 at 14 17 16" src="https://github.com/aralroca/next-translate/assets/13313058/38596298-0a00-4e1c-b5fa-f5427b73c608">

Probably is for the space and we need to update this regex to ` /<(\w+)>(.*?)<\/\1>|<(\w+) *\/>/`. 

Feel free to PR this fix 😊

**Comment by MonstraG** [comment]
This is still happening but no longer a problem, so I'm gonna close this
