### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by zakidze** [aralroca/next-translate#1069]
**What version of this package are you using?**
2.0.6 but is same for all

**What operating system, Node.js, and npm version?**

**What happened?**

**What did you expect to happen?**
nohting it works normal

**Are you willing to submit a pull request to fix this bug?**

**Comment by aralroca** [comment]
Duplicated https://github.com/aralroca/next-translate/issues/1029

**Comment by zakidze** [comment]
yes its deplucated but any solotion is provided? i searched all issue befor posting this one
