### ISSUE TITLE
Next 13 app dir - Error: Dynamic server usage: force-dynamic

### ISSUE THREAD

**Issue by darr1s** [aralroca/next-translate#1078]
![image](https://github.com/aralroca/next-translate/assets/21124691/6f973a87-ba21-48f2-8375-e9355b581da8)

**What version of this package are you using?**
```
    "next-translate": "^2.3.1",
    "next-translate-plugin": "^2.3.0",
```

**What operating system, Node.js, and npm version?**
```
npm v18.16
pnpm v8.6.3
```

**What happened?**
1. I followed exactly app-dir examples and facing this in every page navigate

**Extra information**
```
module.exports = {
  locales: ["default", "en", "ms"],
  defaultLocale: "default",
  localeDetection: false,
  pages: {
    "*": ["common"],
    "/[lang]": ["common"],
  },
}
```

**Comment by aralroca** [comment]
Interesting... We are using [`export const dynamic = 'force-dynamic'`](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic) to allow dynamic rendering inside (`/[lang]`). However, I never experimented this issue before. Would be great if you change a reproducible example to investigate why this is happening 🙏 

BTW; for now you can change this [`dynamic`](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic) behavior, by adding this to the page `export const dynamic = 'auto'`.

**Comment by aralroca** [comment]
Please @darr1s try this prerelease and give some feedback 🙏

- Next-translate: `2.4.0-canary.4`
- Next-translate-plugin: `2.4.0-canary.4`

**Comment by darr1s** [comment]
Thanks! I've upgraded to canary 4 and dynamic seems to throw a new error from the lib:

```Unhandled Runtime Error
Error: Dynamic server usage: searchParams.lang

Source
src/app/[lang]/login/page.tsx (80:20) @ searchParams

  78 | const config = { 
  79 |   ...__i18nConfig,
> 80 |   locale: props.searchParams?.lang ?? props.params?.lang ?? __i18nConfig.defaultLocale,
     |                ^
  81 |   loaderName: 'server /page',
  82 |   pathname: '/[lang]/login/',
  83 |   loadLocaleFrom: typeof __i18nConfig.loadLocaleFrom === 'function' ? __i18nConfig.loadLocaleFrom : (l, n) => import(`@next-translate-root/locales/${l}/${n}`).then(m => m.default),
```

**Comment by aralroca** [comment]
@darr1s thanks for the feedback

**Comment by aralroca** [comment]
I guess is related with this Next.js issue https://github.com/vercel/next.js/issues/49182. But in reality `searchParams` is not necessary to use it, I changed the order prioritizing `params`, in this way is not necessary to add the `export const dynamic = 'force-dynamic'` that they comment in the Next.js issue.

**Comment by aralroca** [comment]
I hope now works in your case:


- Next-translate: `2.4.0-canary.4`
- Next-translate-plugin: **`2.4.0-canary.5`**

**Comment by aralroca** [comment]
Any news @darr1s ? 😊

**Comment by darr1s** [comment]
> Any news @darr1s ? 😊

Hey! Pardon I forgot to close the issue. It worked, but I'm faced with some issue where Next 13 will hang the browser to death (I'm thinking is the middleware prefetch or redirection) and not related to this issue anymore.

Thanks for the help!

**Comment by aralroca** [comment]
Ok I'll close this issue, if you found that is related with next-translate feel free to report another issue. Thanks for your feedback ☺️
