### ISSUE TITLE
Change language does not trigger a re-render on all client compoments (App Directory)

### ISSUE THREAD

**Issue by mwerder** [aralroca/next-translate#1079]
**What version of this package are you using?**
"next-translate": "^2.3.1",
"next-translate-plugin": "^2.3.0"
"next": "13.4.6",

**What operating system, Node.js, and npm version?**
macOS: Ventura 13.3.1
node: 18.14.2
npm 9.5.0

**What happened?**
I tried to follow your guide and I noticed that after switching the language, it will not update every component.
So I built the app according to your [example](https://github.com/aralroca/next-translate/tree/master/examples/with-app-directory), but I added a second ClientComponent.
Only the first Client Component will change the language correctly. The second component is always one state/render behind.
I also saw that the 'first' client component will re-render twice, while the second only has one re-render.
When triggering a re-render by changing its state with the counter, the language will update correctly.

Here's the [code](https://github.com/mwerder/test-next-translate), but it's basically the same as in your example.

https://github.com/aralroca/next-translate/assets/16059443/501b0c87-ef20-4b2a-9b5b-5ed934484bd6

**What did you expect to happen?**
The language of all components should change

**Are you willing to submit a pull request to fix this bug?**
Sure, but I guess I'll need a little help

**Comment by aralroca** [comment]
@mwerder can you verify if is happening in the last prerelease?

- Next-translate `2.4.0-canary.4`
- Next-translate-plugin `2.4.0-canary.4`

You need to update both in the same version. Thanks for the feedback 🙏

**Comment by mwerder** [comment]
@aralroca thanks for the fast answer, seems to work on the canary versions 👏

**Comment by aralroca** [comment]
Ok perfect! Thanks for the feedback! Then I will close the issue. I hope to release it 2.4 at the ends of this week
