### ISSUE TITLE
Peer dependency error when updating to 2.4.0-canary.5

### ISSUE THREAD

**Issue by EricImpact** [aralroca/next-translate#1081]
**What version of this package are you using?**

2.4.0-canary.5

**What operating system, Node.js, and npm version?**

MacOS - Ventura 13.4
Node 18.16.0
npm 9.5.1 

**What happened?**

I got a peer dependency error from NPM when trying to update to 2.4.0-canary.5 for next-translate and next-translate-plugin: 

![Screenshot 2023-06-23 at 9 52 12 am](https://github.com/aralroca/next-translate/assets/133611259/01ece4c4-f7cd-4033-96ac-3e4aad05c590)

**What did you expect to happen?**

I expected to be able to upgrade without any problems. 

**Are you willing to submit a pull request to fix this bug?**

Sure, though I don't really understand why the peer dependency error is occurring.

---

Here is my package.json:

```
{
  "name": "next-translate-example",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "20.3.1",
    "@types/react": "18.2.13",
    "@types/react-dom": "18.2.6",
    "autoprefixer": "10.4.14",
    "eslint": "8.43.0",
    "eslint-config-next": "13.4.6",
    "next": "13.4.6",
    "next-translate": "^2.4.0-canary.5",
    "postcss": "8.4.24",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.2",
    "typescript": "5.1.3"
  },
  "devDependencies": {
    "next-translate-plugin": "^2.4.0-canary.5"
  }
}
```

I'm at a loss as to why the peer dependency check is failing. If I'm reading it correct, `next-translate-plugin` is indicating a peer dependency of `next-translate` 2.3.0 or greater — which our version of 2.4.0-canary.5 clearly satisfies.

**Comment by aralroca** [comment]
I think is related wit this npm issue for canary versions https://github.com/npm/cli/issues/4958 probably in the last npm version this is already fixed. However dont worry I'm going to update the peerDependencies before the release. For now to try the canary version you can force, update npm or use yarn or pnpm
