### ISSUE TITLE
Client component translations are coming one step back.

### ISSUE THREAD

**Issue by kod-man** [aralroca/next-translate#1084]
**What version of this package are you using?** 2.3.1

**What operating system, Node.js, and npm version?** NodeJs=> 16.17.1 Npm=> 8.15.0 Next=>13.4.4

**What happened?**

If I change the language using the language switcher component, Client components' translations are coming one step back.

If I choose French as a default language it works as expected at first.

![Screenshot 2023-06-23 at 22 43 21](https://github.com/aralroca/next-translate/assets/54946794/a4c58175-e321-4273-9ce1-8b6f4691e20d)

Then if I change the language to Dutch, as you can see the buttons translations are still French

![Screenshot 2023-06-23 at 22 44 46](https://github.com/aralroca/next-translate/assets/54946794/33da85e9-1bc9-4a02-a039-7f3a35532c59)

Then If I change the language to English, now buttons translations are Dutch(one step back)

![Screenshot 2023-06-23 at 22 46 47](https://github.com/aralroca/next-translate/assets/54946794/46977ea3-36c9-4c82-a4a6-cf822057a41d)

My language switcher component

```
'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

const LanguageOptions = [
  { label: 'English', value: 'en' },
  { label: 'Français', value: 'fr' },
  { label: 'Nederlands', value: 'nl' },
];

export default function LanguageSwitcher() {
  const pathname = usePathname();
  const pathArray = pathname.split('/');
  //Remove the first two elements from an array
  const pathWithoutLang = pathArray.slice(2);
  // join the array back to a string
  const newPath = pathWithoutLang.join('/');

  return (
    <div className='px-1 bg-gray-200 rounded-lg outline-0'>
      {LanguageOptions.map((locale) => (
        <>
          <Link
            key={locale.label}
            href={`/?lang=${locale.value + '/' + newPath}`}
            as={`/${locale.value + '/' + newPath}`}
          >
            {locale.value}
          </Link>
          <br />
        </>
      ))}
    </div>
  );
}

```

**app/[lang]/layout.tsx**

```
import { Inter } from 'next/font/google';
import { redirect } from 'next/navigation';
import React from 'react';
import i18n from '../../i18n';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by creating next app',
};

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  // Redirect to default locale if lang is not supported. /second-page -> /en/second-page
  if (!i18n.locales.includes(lang)) {
    redirect(`/${i18n.defaultLocale}/${lang}`);
  }

  return (
    <html lang={lang}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
```

i18n.js

```
module.exports = {
  locales: ['en', 'fr', 'nl'],
  defaultLocale: 'en',
  pages: {
    '*': ['common'],
    '/[lang]': ['form', 'login'],
    '/[lang]/deneme': ['login', 'form'],
    '/[lang]/onboarding': ['common'],
    '/[lang]/signup': ['common', 'signup', 'login', 'form'],
  },
};
```

**// middleware.ts**
```
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import i18n from './i18n';

// /es/page-name -> rewrites to -> /es/page-name?lang=es
export function middleware(request: NextRequest) {
  const locale = request.nextUrl.locale || i18n.defaultLocale;
  request.nextUrl.searchParams.set('lang', locale);
  return NextResponse.rewrite(request.nextUrl);
}
```

**What did you expect to happen?**

I want to use Next js' new app directory with next-translate. I expect that rendering client/server components together with multiple languages 

**Are you willing to submit a pull request to fix this bug?**

**Comment by aralroca** [comment]
Try the latest 2.4.0 version please

**Comment by aralroca** [comment]
BTW; you can remove the middleware

**Comment by kod-man** [comment]
Thank you it fixed the issue. 🥳  I appreciate your help.
