### ISSUE TITLE
Using browser's back button causes freezing

### ISSUE THREAD

**Issue by kod-man** [aralroca/next-translate#1086]
**What version of this package are you using?** 2.4.0

**What operating system, Node.js, and npm version?** NodeJs=> 16.17.1 Npm=> 8.15.0 Next=>13.4.4

**What happened?**

If I navigate to the next page by using the Link component below, if works fine.

```
<Link
          className={buttonVariants({
            variant: 'default',
          })}
          href={`/${lang}/signup`}
        >
          {t('register')}
</Link>
```

But if I want to go to the previous page by using the browser's back button, the page content is remaining same, and 5 sec later it is freezing

**Situation 1: Normal** 

![Screenshot 2023-06-24 at 17 41 08](https://github.com/aralroca/next-translate/assets/54946794/8bceafc2-a982-43dd-a507-61c6b16123a6)

**Situation 2: Navigated back by clicking the back button but the content remained the same even though the link changed** 

![Screenshot 2023-06-24 at 17 41 37](https://github.com/aralroca/next-translate/assets/54946794/9916d590-6965-4b41-a1e8-93d3584a01e6)

Unfortunately, it is starting to freeze

![Screenshot 2023-06-24 at 16 53 43](https://github.com/aralroca/next-translate/assets/54946794/e81a04dd-46a6-4579-bbde-ae5c79a399ba)

**What did you expect to happen?**

I want to see previous page without any problem
**Are you willing to submit a pull request to fix this bug?**

**Comment by aralroca** [comment]
Probably related with this bug https://github.com/aralroca/next-translate/issues/1085#issuecomment-1605604189

**Comment by kod-man** [comment]
> Probably related with this bug [#1085 (comment)](https://github.com/aralroca/next-translate/issues/1085#issuecomment-1605604189)

I suppose there is no temporary solution for now ?

**Comment by aralroca** [comment]
Just was reported today. I have a solution in terms of next-translate-plugin that should fix this. I'm going to give you feedback about this later.

**Comment by aralroca** [comment]
@kod-man please try:

- Next-translate: [`2.4.1`](https://github.com/aralroca/next-translate/releases/tag/2.4.1)
- Next-translate-plugin: [`2.4.1`](https://github.com/aralroca/next-translate-plugin/releases/tag/2.4.1)

And give feedback if is working now in your case! Thanks!

**Comment by kod-man** [comment]
> @kod-man please try:
> 
> * Next-translate: [`2.4.1`](https://github.com/aralroca/next-translate/releases/tag/2.4.1)
> * Next-translate-plugin: [`2.4.1`](https://github.com/aralroca/next-translate-plugin/releases/tag/2.4.1)
> 
> And give feedback if is working now in your case! Thanks!

Hey @aralroca yes it fixed my issue thanks for being so responsive 🙏

**Comment by aralroca** [comment]
Cool @kod-man thanks for your feedback and your contribution reporting this issue
