### ISSUE TITLE
Bug with lang and translations in nested layout

### ISSUE THREAD

**Issue by Besuf** [aralroca/next-translate#1090]
**What version of this package are you using?**
v2.4.2

**What operating system, Node.js, and npm version?**
Windows, node v18.16.0, npm v9.7.1
**What happened?**
I'm encountering a strange bug related to lang and translations when working with pages within a nested layout. The issue is that while the outer pages correctly display the lang, the pages inside the nested layout only show the default locale as lang, regardless of the actual language selected.

This issue is particularly puzzling because initially, I couldn't reproduce it using the official with-app-directory example. However, after some experimentation, it appears that the cause might be related to a specific loading component that needs to be marked with the "use client" directive to prevent this problem. I'm unsure of the correlation between the loading component and next-translate, and how this issue can occur.

I have created a CodeSandbox example that closely resembles the official example. You can find the example [here](https://codesandbox.io/p/github/Besuf/nta-test/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljdxj4va000b356s3j99b2sd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljdxj4va000d356sl9hnyc42%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljdxj4va000b356s3j99b2sd%2522%253A%257B%2522id%2522%253A%2522cljdxj4va000b356s3j99b2sd%2522%252C%2522activeTabId%2522%253A%2522cljdxluve0060356s9zxz90yi%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljdxj4va000a356sjtyfeu53%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp%252F%255Blang%255D%252Ftest-app%252Floading.tsx%2522%252C%2522id%2522%253A%2522cljdxluve0060356s9zxz90yi%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522cljdxj4va000d356sl9hnyc42%2522%253A%257B%2522id%2522%253A%2522cljdxj4va000d356sl9hnyc42%2522%252C%2522activeTabId%2522%253A%2522cljdxk0u900dx356sgaa2h2ih%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cljdxjw7f009o356s24szky6i%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cljdxk0u900dx356sgaa2h2ih%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fen%252Ftest-app%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). Please take note of the two layout components in the page and how the lang is incorrectly displayed in the last child element. If you uncomment the "use client" directive either inside the [lang] or [lang]/test-app folder, the issue is resolved.

I would appreciate any insights or suggestions on how to resolve this issue. Thank you for your help!
**What did you expect to happen?**
I expect the lang and translations to work correctly without the need for the 'use client' directive in my loading component.
**Are you willing to submit a pull request to fix this bug?**

**Comment by Besuf** [comment]
@aralroca Are there any updates on this bug? It's still happening in the latest version 2.4.4.
Or, please let me know if you have an explanation on how to avoid it in the future.

**Comment by aralroca** [comment]
@Besuf I'm going to take a look. Thanks to report it

**Comment by aralroca** [comment]
@Besuf try the prerelease `2.5.0-canary.1` for `next-translate-plugin` and please give feedback if is working now in your case. Thanks!! 😊
