### ISSUE TITLE
Hydration error in production

### ISSUE THREAD

**Issue by akhdefault** [aralroca/next-translate#1094]
**What version of this package are you using?**
I am [using this example](https://github.com/vercel/next.js/tree/canary/examples/with-next-translate)
**What operating system, Node.js, and npm version?**
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.4.7
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.5.2
**What happened?**
I clone project using `npx create-next-app --example with-next-translate with-next-translate-app`, then run `yarn build && yarn start` and open `http://localhost:3000/en`; I get a blank page and error: 'Hydration failed because the initial UI does not match what was rendered on the server.'
**What did you expect to happen?**
I expect the page to work, like in dev mode
**Are you willing to submit a pull request to fix this bug?**
I might (it depends)

**Comment by aralroca** [comment]
@akhdefault would you try the latest version of next-translate & next-translate-plugin?

**Comment by akhdefault** [comment]
@aralroca Yep, checked it with "next-translate" and "next-translate-plugin" both at 2.4.4, same result.

**Comment by aralroca** [comment]
it's a curious bug... Because there are no client components as it crashes during hydration...

**Comment by aralroca** [comment]
I was surprised that this repo was crashing and not others. I have compared the server and client HTML and I see that the server one doesn't have the html tags, head and the client one does. It seems that they are not being specified in the layout.

Changing the layout to this one fixes this hydration bug:

```js
import useTranslation from 'next-translate/useTranslation'
import './style.css'

export const metadata = {
  title: 'Next.js',
}

export default function Layout(props) {
  const { t, lang } = useTranslation()
  return (
    <html lang={lang}>
      <head />
      <body className="container">
        {props.children}
        <footer>
          <span>{t('common:powered')} </span>
          <a href="https:vercel.com" target="_blank" rel="noopener noreferrer">
            ▲ vercel
          </a>
          <span>&amp;</span>
          <a
            href="https:github.com/vinissimus/next-translate"
            target="_blank"
            rel="noopener noreferrer"
          >
            next-translate
          </a>
        </footer>
      </body>
    </html>
  )
}
```



Thanks for reporting it, I will now do the PR in Next.js to fix the example. On the other hand, I'm closing the issue because it's not an issue with our library, but we made the example wrong. Thank you very much @akhdefault
