### ISSUE TITLE
Next-translate overriding custom middleware and query parameters

### ISSUE THREAD

**Issue by Besuf** [aralroca/next-translate#1095]
**What version of this package are you using?**
V2.4.4

**What operating system, Node.js, and npm version?**
Windows 11, node v18.6.0, npm v9.7.1
**What happened?**
I have encountered an issue with the Next-translate package where it overrides custom middleware and interferes with query parameters. Although Next-translate automatically reads the lang parameter, it is causing problems when trying to create custom middleware for handling redirects and rewriting URLs.

In my scenario, I need to redirect /en/example-page to /example-page and rewrite the content with /en/example-page. To achieve this, I have added the following code in my custom middleware:`request.nextUrl.searchParams.set("lang", defaultLocale);` followed by `return NextResponse.rewrite(request.nextUrl);`  However, Next-translate overrides this logic and when I navigate to /example-page, the lang parameter I set is omitted and it becomes `params:{lang: example-page}`. If I remove the Next-translate wrapper, the parameters are correctly passed to the page, `params:{lang:en}`.

I would appreciate any guidance on the documentation regarding creating custom middleware or if there is a way to disable the part of the Next-translate package that overrides the query parameter. It would be helpful to have more information on how to work around this issue.

Attached below is the middleware logic for reference. Please note the last if block where I am rewriting the page if the valid locale cannot be found from the path."
```javascript
function middleware(request: NextRequest) {
  const pathname = request.nextUrl.pathname;
  const originalPath = new URL(request.url).pathname;
  const currentLocale = getLocale(originalPath);

  // Check if the default locale is in the pathname
  if (currentLocale === defaultLocale) {
    // we want to REMOVE the default locale from the pathname,
    // and later use a rewrite so that Next will still match
    // the correct code file as if there was a locale in the pathname
    const result = originalPath.replace(`/${defaultLocale}`, "");
    const newUrl = new URL(result, request.nextUrl.origin + "/");

    return NextResponse.redirect(newUrl);
  }

  const pathnameIsMissingValidLocale = !locales.find(
    (locale) => locale === currentLocale
  );

  if (pathnameIsMissingValidLocale) {
    const newUrl = new URL(
      `/${defaultLocale}${pathname}`,
      request.nextUrl.origin
    );

    request.nextUrl.href = newUrl.href;
    request.nextUrl.pathname = newUrl.pathname;
    request.nextUrl.searchParams.set("lang", defaultLocale);
    newUrl.searchParams.set("lang", defaultLocale);

    // rewrite it so next.js will render `/` as if it was `/pl`
    return NextResponse.rewrite(request.nextUrl);
  }
}
```
**What did you expect to happen?**
I expect my custom middleware's parameter setup to be preserved after rewriting the page.
**Are you willing to submit a pull request to fix this bug?**
I might if it's not very complicated

**Comment by aralroca** [comment]
I think is related with the breaking change from Next.js >= 13.2, we explained in the 2.3 release notes: https://github.com/aralroca/next-translate/releases/tag/2.3.0 we proposed a solution without the middleware meanwhile this is not fixed in the Next.js repo. The Next.js issue is this one: https://github.com/vercel/next.js/issues/49883

**Comment by Besuf** [comment]
@aralroca Thanks for the quick response. I hope the Nextjs team resolves this quickly. Because the current proposed solution (redirecting inside at the component-level) might have negative performance and SEO implicaitons.

**Comment by Besuf** [comment]
I'm not entirely sure if this issue is specifically related to next-translate because the official example of Next13 with appdir i18n routing appears to correctly rewrite or redirect params in the latest Next.js version (https://github.com/vercel/next.js/blob/canary/examples/app-dir-i18n-routing/middleware.ts). It's possible that the issue arises from having the next-translate-plugin defined inside next-config.js. @aralroca, I can confirm that rewriting and redirecting work if the next-translate-plugin is removed from next.config.js.

**Comment by aralroca** [comment]
The problem comes using i18n inside next.config.js: https://github.com/vercel/next.js/blob/07591042870766a6d846263e28d3a9400a5bd3e6/examples/app-dir-i18n-routing/next.config.js#L8

Our plugin is adding the i18n routing. The idea is to keep this to allow partial migrate from pages to app router. But looks that this i18n config of Next.js is breaking the middleware with app router...

**Comment by aralroca** [comment]
I'm going to close this issue because is out of the scope of our library. This should be fixed after Next.js fixes this issue: https://github.com/vercel/next.js/issues/49883
