### ISSUE TITLE
React Server Component loads the wrong namespace in subpages

### ISSUE THREAD

**Issue by zifeo** [aralroca/next-translate#1102]
**What version of this package are you using?**

Latest, full repo is available [here](https://github.com/zifeo/next-translate-repro/).

**What operating system, Node.js, and npm version?**

Latest macOs, node v20.3.1 and pnpm 8.6.6.

**What happened?**

[Changing](https://github.com/zifeo/next-translate-repro/blob/main/app/%5Blang%5D/blog/page.tsx#L1) the page from client-side to server-side breaks the translation in a subpage. The key is found on the client side, but on the server side it is unknown. We backtracked the issue to the namespace loaded. 

See the console in the repro:
```
// client
namespace { blog: { 'this-key-should-exist': 'blog-fr' } }

// server
namespace { home: { Banner: { subtitle: 'French style' } } }
```

**What did you expect to happen?**

Getting same translations in client side and server side.

**Are you willing to submit a pull request to fix this bug?**

Issue seems deep inside the nextTranslate logic, not sure I am the best suited for that.

**Comment by aralroca** [comment]
Can you verify if is happening in the latest canary version? thanks!

**Comment by zifeo** [comment]
@aralroca Did you manage to find something? Is there something more I can help with?

**Comment by aralroca** [comment]
@zifeo I have not been able to yet. I will look into it this week

**Comment by aralroca** [comment]
Already resolved in [2.5.0-canary.3](https://github.com/aralroca/next-translate-plugin/releases/tag/2.5.0-canary.3)

**Comment by aralroca** [comment]
@zifeo can you confirm that now is working fine in your project? Thanks

**Comment by zifeo** [comment]
@aralroca just tested with 2.5.0 and it looks ok, thanks 💯
