### ISSUE TITLE
in this repo examples : Critical dependency: the request of a dependency is an expression 

### ISSUE THREAD

**Issue by zakidze** [aralroca/next-translate#1104]
**What version of this package are you using?**
2.4.4 but same with all versions
i know this is duplicated but any solotions....????

**What happened?**
after downloading app directory example and install it and run the dev server this happen:
Critical dependency: the request of a dependency is an expression 

**What did you expect to happen?**
it worknormlally

here the package json
{
  "name": "-",
  "version": "1.0.0",
  "private": true,
  "license": "MIT",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "analyze": "ANALYZE=true yarn build"
  },
  "dependencies": {
    "@mdx-js/loader": "2.3.0",
    "@mdx-js/react": "2.3.0",
    "@next/mdx": "13.4.7",
    "next": "13.4.7",
    "next-translate": "2.4.4",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@next/bundle-analyzer": "13.4.6",
    "@types/node": "20.3.1",
    "@types/react": "18.2.12",
    "next-translate-plugin": "2.4.4",
    "typescript": "5.1.3"
  },
  "resolutions": {
    "webpack": "5.11.1"
  }
}

**Comment by aralroca** [comment]
Duplicated of https://github.com/aralroca/next-translate/issues/1029
