### ISSUE TITLE
Translation key suggestion will be incorrect if the key is in snake_case

### ISSUE THREAD

**Issue by loukhin** [aralroca/next-translate#1114]
**What version of this package are you using?**
2.5.0

**What operating system, Node.js, and npm version?**
macOS 14.0 (Sonoma preview)
Node.JS v18.10.0

**What happened?**
If the translation key was in snake case, for example `HELLO_WORLD`
<img width="188" alt="image" src="https://github.com/aralroca/next-translate/assets/29707893/57c95f19-95f1-4743-a3a6-cf91b64a2c5a">
then the suggested translation key will be `HELLO`, which is incorrect
<img width="152" alt="image" src="https://github.com/aralroca/next-translate/assets/29707893/392cb880-15a6-4c83-8503-d28306f4bf19">

**What did you expect to happen?**
the suggested translation key showing `HELLO_WORLD`
<img width="174" alt="image" src="https://github.com/aralroca/next-translate/assets/29707893/7d526d8d-017f-48de-951f-ae022aaae5ad">

**Are you willing to submit a pull request to fix this bug?**
I can try

possible fix is changing [`_${infer Num}`](https://github.com/aralroca/next-translate/commit/f1524192f39b00610f135b33d1663bc089c759a6#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405R178) to `_${number}`

**Comment by aralroca** [comment]
Good catch. Thanks to report It! Feel free to PR!
