### ISSUE TITLE
Custom app _app getInitialProps not running

### ISSUE THREAD

**Issue by danielpid** [aralroca/next-translate#1116]
**What version of this package are you using?**
2.5.0

**What operating system, Node.js, and npm version?**
macOS Monterrey, node v16.15.1, npm 8.11.0

**What happened?**
I'm using Nextjs and next-translate in an nx monorepo. I have a custom app on _app with a getInitialProps that I use for initializing different tools. With Nextjs 12.3.1 and next-translate 1.6.0, everything was working fine.

I upgraded Nextjs from 12.3.1 -> 13.4.10. At this point, I got an error because the i18n config file couldn't be found despite having the NEXT_TRANSLATE_PATH env var defined. There was a thread suggestion to change that env var value to '../../' for dev and './' for production. This worked after I upgraded next-translate to 2.5.0.

The problem I have at the moment is that the function getInitialProps in _app doesn't run. 

**What did you expect to happen?**
I want the MyApp.getInitialProps to run.

**Are you willing to submit a pull request to fix this bug?**
Yes

**Comment by danielpid** [comment]
After checking the code I realized this problem comes from next-translate-plugin and there's already an issue created there https://github.com/aralroca/next-translate-plugin/issues/8. I'll follow up there.
Thanks!

**Comment by aralroca** [comment]
I guess is related that we replaced all regex to the typescript parser to detect the loaders.

**Comment by aralroca** [comment]
@all-contributors please add @danielpid for code

**Comment by aralroca** [comment]
Fixing also pageExtensions like `_app.pages.js` in https://github.com/aralroca/next-translate-plugin/issues/35. @all-contributors please add @TheMatrixan for code
