### ISSUE TITLE
Next 13 app directory: Error pages not working

### ISSUE THREAD

**Issue by fbnptrs** [aralroca/next-translate#1126]
**What version of this package are you using?**
next-translate `2.5.2` with next `13.4.12`

**What operating system, Node.js, and npm version?**
Node `18.17.0` with pnpm `8.6.3`

**What happened?**
Following the Next error handling guidance for app directory (https://nextjs.org/docs/app/building-your-application/routing/error-handling), using an `error.tsx`, the following error occurs:
![image](https://github.com/aralroca/next-translate/assets/48057106/1f9ba9fe-93bd-45c5-a13c-3454c8fa4f9b)

Is there something I am missing in terms on configuration? Unfortunately the docs are not mentioning anything specific to error handling.

**What did you expect to happen?**
Error page loading as expected, without any issue as described in Next docs.

**Comment by nirtamir2** [comment]
I Have the same error. You can replicate it easily if you have 2 "use client" pages A and B, you navigate from A to B and then press the browser back button. 
```
    "next-translate-plugin": "^2.5.2"
    "next-translate": "^2.5.2",
```

**Comment by aralroca** [comment]
@nirtamir2 @fbnptrs should be fixed in next-translate-plugin [2.5.3-canary.3](https://github.com/aralroca/next-translate-plugin/releases/tag/2.5.3-canary.3) prerelease. Would be great if you can verify that is working fine now in your projects before the release. Thanks!

**Comment by fbnptrs** [comment]
@aralroca yep, it fixes the issue in my project with the next-translate-plugin [2.5.3-canary.3](https://github.com/aralroca/next-translate-plugin/releases/tag/2.5.3-canary.3) prerelease. Thanks for the quick response!

**Comment by aralroca** [comment]
amazing @fbnptrs , thanks for your feedback and contribution. I'm going to do the release soon!
