### ISSUE TITLE
Error: Cannot find module 'next-translate-plugin'

### ISSUE THREAD

**Issue by marcusnunes** [aralroca/next-translate#1145]
**What version of this package are you using?**
2.5.3

**What operating system, Node.js, and npm version?**
MacOS: 12.6.9 Monterey
Node.js: v16.20.0
Yarn 1.22.4

**What happened?**
I have `next-translate-plugin` in my `devDependencies` but I'm getting this error:

<img width="819" alt="Screen Shot 2023-09-21 at 15 36 13" src="https://github.com/aralroca/next-translate/assets/9219767/ae8807c1-b25f-4d03-8b2b-eedefe70a594">

``` 
'next-translate-plugin' should be listed in the project's dependencies. Run 'npm i -S next-translate-plugin' to add it
```

Because of that, we I try to build in prodution I'm getting this other error:
```
out: $ next build
err:  ⨯ Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
err: > Build error occurred
err: Error: Cannot find module 'next-translate-plugin'
```
<img width="400" alt="Screen Shot 2023-09-21 at 15 39 21" src="https://github.com/aralroca/next-translate/assets/9219767/db54d401-9d1d-45b5-84c3-f864eaafe0e0">

**What did you expect to happen?**
Work as a devDependencies.
I'm still using `next-translate 1.6.0` because of that.

**Are you willing to submit a pull request to fix this bug?**

**Comment by joeltio** [comment]
I have this same problem and https://github.com/aralroca/next-translate-plugin/issues/65 suggests to put `next-translate-plugin` in dependencies instead of dev dependencies. After doing so it works for me.

**Comment by aralroca** [comment]
Duplicated of https://github.com/aralroca/next-translate-plugin/issues/65
