### ISSUE TITLE
Can't resolve 'next-translate/appWithI18n' on 2.7.0-canary.1

### ISSUE THREAD

**Issue by acidfernando** [aralroca/next-translate#1181]
**What version of this package are you using?**
2.7.0-canary.1

**What operating system, Node.js, and npm version?**
macOS 12.2.1, NodeJS version: 20.9.0, npm version: 10.1.0. NextJS: 13.5.6 (not app folder)

**What happened?**
Running the app (building or with dev server) throws the error on the title.

**What did you expect to happen?**
Not to throw

**Are you willing to submit a pull request to fix this bug?**
With some clues as to where to look, yes

**Comment by aralroca** [comment]
I can't reproduce it @acidfernando . Can you try with [3.0.0-canary.1](https://github.com/aralroca/next-translate/releases/tag/3.0.0-canary.1) in both (next-translate & next-translate-plugin) ? Thanks

**Comment by acidfernando** [comment]
With that version I'm getting `Module not found: Can't resolve 'next-translate-plugin/loader'`. I'll try to create a repro

**Comment by acidfernando** [comment]
Here's a repro: https://codesandbox.io/p/devbox/next-translate-build-hk9t38

Maybe I'm doing something wrong? Same code works correctly on v2.6.2

Also, this repro uses app router, but the project I first reported the bug was on pages router.


Hope it helps!

**Comment by aralroca** [comment]
Ok, looks like a problem generating the tarball of npm that avoids adding some necessary files. Thanks to report

**Comment by acidfernando** [comment]
Yes, that did it. Thanks for the fix!
