### ISSUE TITLE
Cold Start on dynamic routes

### ISSUE THREAD

**Issue by maclementED** [aralroca/next-translate#1183]
**What version of this package are you using?**
- `next`: 13.5.6
- `next-translate`: 2.6.1
- `next-translate-plugin`: 2.6.1

**What operating system, Node.js, and npm version are you using?**
- Node.js version: v18.19.0

**What happened?**
When reaching a dynamic URL like `/org/[slug]`, fetching the translation using SSR can take more than 1 second (average around ~300ms) for the initial load, and then it drops to <100ms once cached.

My assumption is that Next.js has a cold start issue. Since the translation is the same regardless of the slug, I was wondering if there is a way to always fetch the same route to bypass the NextJs Issue.

**What did you expect to happen?**
The time to load the translation file should always be less than <100ms.

**Are you willing to submit a pull request to fix this bug?**
If I knew how to fix it.

**Comment by aralroca** [comment]
how are you fetching the translations? I don't think we can solve much from the library about how the Next.js cache works and the connection time with your external translation service.

The easiest thing to do is to use the translations in the repository itself, so you avoid any extra requests.

**Comment by aralroca** [comment]
You can use:

```ts
// 'force-cache' is the default, and can be omitted
fetch('https://...', { cache: 'force-cache' })
```

https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#caching-data

**Comment by maclementED** [comment]
Here are more information on my setup:

**i18n.json**
```
{
  "locales": [
    "en",
    "fr-CA"
  ],
  "defaultNS": "common",
  "defaultLocale": "en",
  "localeDetection": true,
  "pages": {
    "*": ["common"],
    "/login":["login"],
    // ...
  }
}
```
And im using `nextTranslate` from `next-translate-plugin` in my `next.config.js`. My translation files are simply hosted on Vercel (/public folder).

If you think it's an issue on Vercel itself, should I use the I18nProvider instead for those routes ?

**Comment by aralroca** [comment]
@maclementED I don't understand the question, what do you mean by these routes?

**Comment by maclementED** [comment]
After more research this is a Vercel Hosting Issue and not `next-translate`.
