### ISSUE TITLE
lang useTranslation hook not refreshing in sitemap page

### ISSUE THREAD

**Issue by erwanriou** [aralroca/next-translate#1203]
**What version of this package are you using?**
2.6.2
**What operating system, Node.js, and npm version?**
20 & 10
**What happened?**

building a multi vendor website such as 

www.example.com
www.example.com.br
etc

using the middleware solution

```js
export function middleware(request) {
  const locale = request.nextUrl.locale || i18n.defaultLocale
  request.nextUrl.searchParams.set("lang", locale)
  request.nextUrl.href = request.nextUrl.href.replace(`/${locale}`, "")
  console.log("LOCALE", locale)
  console.log("URL", request.nextUrl.href)
  return NextResponse.rewrite(request.nextUrl)
}
```

i can see that the locale is refreshed correctly here but unless i go to another page explicitly the sitemap type page is not refreshing the locale (even from a different vendor) and still serve the last previous one fetched

```js
const LegalSitemap = async () => {
  // LOAD DATA
  const { lang } = useTranslation()
  const { legal } = await getLegalsServer({ countryCode: lang })
  const { domain } = domains?.find(({ defaultLocale }) => defaultLocale === lang)

  console.log("LOCALE INSIDE SITEMAP", lang)

  return legal?.map(l => ({
    url: `https://${domain}/legal/${l?.management?.url}`,
    lastModified: l?.lastEditDate,
    changeFrequency: "yearly"
  }))
}
```

![Screenshot from 2024-03-27 11-55-46](https://github.com/aralroca/next-translate/assets/30130006/84a61468-58e6-47e5-a525-3559fa42c107)

**What did you expect to happen?**

i would expect that the `const { lang } = useTranslation()` to be refreshed and displayed the updated local.

**Are you willing to submit a pull request to fix this bug?**

if i know where to look, definitly!

**Comment by erwanriou** [comment]
I investigated a bit the code but i just can get to find that `global.__NEXT_TRANSLATE__.lang` but not sure how to make it refresh from the middleware.

**Comment by aralroca** [comment]
@erwanriou are you using app router or pages router?

**Comment by erwanriou** [comment]
> @erwanriou are you using app router or pages router?

app router. I used your library with the pages router and it work fine there. The issue occure also on the `not-found` page too somehow. I found a fix but it's a bit dirty...
