### ISSUE TITLE
Big loading times and scroll to top once loaded

### ISSUE THREAD

**Issue by Graffalo92** [aralroca/next-translate#1204]
I am using latest next translate with next js 14.1.4 and pages router. I have an issue where in dynamic pages the props are taking a lot of time to respond once uploaded to vercel.  Sometime it might take 4-12 seconds some other below 1 second. And always load last. what i mean is i first see the dom i scroll down the bit and once the translations are fetched the page scroll up again. 
i18json
{
  "locales": ["en", "es", "pt"],
  "defaultLocale": "en",
  "pages": {
    "*": ["common"]
  }
}
next config 
const withPlugins = require("next-compose-plugins");
const nextTranslate = require("next-translate-plugin");

module.exports = withPlugins([
  [
    nextTranslate,
    {
      reactStrictMode: false,
      distDir: ".next"
    },
  ],
]);

**Comment by aralroca** [comment]
Thanks for reporting it. However, I think is better if you report it to Vercel, it will be a cold-starts problem related to your cloud provider, not to this library. This library by default loads translations with dynamic import.

**Comment by Graffalo92** [comment]
Since i undestand the vercel cold start issue(which is common with next js pages router) i was wondering maybe there is another aproach since all my tranlastions are mostly static data if there is a work around where in dynamic pages the translations are load as static props.
