### ISSUE TITLE
Translation hook does not work with dynamic component (with ReactDOM.render)

### ISSUE THREAD

**Issue by JerryPan** [aralroca/next-translate#226]
I have a component that is created dynamically from ReactDOM.render
Any translations I try inside the target component that I create will only get the key names when doing {t('namespace:keynmame')}

What I should do in such situation? Should it matter how I create the component?

**Comment by aralroca** [comment]
You should provide the `i18nProvider` on top to add the language and namespaces to the context. In theory, this is not necessary for pages because in the build process each page is built with their `i18nProvider` on top.

https://github.com/vinissimus/next-translate#i18nprovider

**Comment by JerryPan** [comment]
Hi @aralroca , thanks for the suggestion. We made it work like you said, with provider wrap around the dynamic component. But there I need to supply a hard-coded namsepaces of the actual language file to the provider.  Our app is exported, how the code can be dynamically loading a different language file, say if I am in a french language - we are using the next-translate because it supports the exported Next with multiple langs per page -- but in this case how the code knows which language file to load?
code example:
`import shared from '../../../locales/en/shared.json';`
` ... `
`<I18nProvider lang={lang} namespaces={{ shared }}>
            <UserTooltipContent userId={userId} />
          </I18nProvider> `

``

**Comment by aralroca** [comment]
@JerryPan did you try using [DynamicNamespaces](https://github.com/vinissimus/next-translate#dynamicnamespaces)?

**Comment by aralroca** [comment]
@JerryPan did you finally try the DynamicNamespaces for this? It should work

**Comment by aralroca** [comment]
@JerryPan ^
