### ISSUE TITLE
Disable Nested translations

### ISSUE THREAD

**Issue by zephyrmathias** [aralroca/next-translate#357]
Hi, is there a way to disable nested translations since my locales key are having `.`

```
{
  "hello.world": "Hello world"
}
```

**Comment by aralroca** [comment]
@zephyrmathias For now `.` is a reserved character for nested translation and there is no way to change it. This is how it works:

https://github.com/vinissimus/next-translate/blob/0.20.2/src/I18nProvider.js#L11

It makes a split. If you want to disable or change it would be a new feature to implement.
