### ISSUE TITLE
Global default namespace

### ISSUE THREAD

**Issue by BjoernRave** [aralroca/next-translate#381]
It would be nice to be able to define a global default namespace, as you can do in I18next.

So that you wouldn't need to write `t('common:hello'), but could just write `t('hello')`.

**Comment by aralroca** [comment]
@BjoernRave in the latest version 0.20.2 you can do this:

```js
const { t } = useTranslation('common') // Default namespace
const text = t('hello') // No need to use common: on front
const anotherNs = t('another-namespace:blabla')
```

This is what you mean? If so, it is already supported from 0.20

**Comment by BjoernRave** [comment]
Yea, I saw that, but I was thinking to have that on a global scale. So I can define it in the `i18n.js` file and the namespace get's loaded on every page, like it does now with: `'*': ['common'],`. Something like: `defaultNS: "common"`

**Comment by aralroca** [comment]
Do you mean as a fallback if the namespace doesn't match?

```js
const { t } = useTranslation('some-namespace') 
const text = t('hello') // "some-namespace:hello", if doesn't exist then return "common:hello"
```

**Comment by BjoernRave** [comment]
yes, that's what I was thinking.

or also 
```
//i18n.js
{
...
"defaultNS": "common"
}


//somefile.js
const { t } = useTranslation()

const text = t('hello') //equal to common:hello
```

**Comment by aralroca** [comment]
Ok @BjoernRave, I marked as a future feature, surely for the 1.1, since we are closing the 1.0! Thank you for the proposal

**Comment by VictorAssis** [comment]
A workaround that I am using is to wrap the useTranslation hook in my own custom hook and use the custom hook in the pages:

```
// utils/translation.js
import useTranslationNext from 'next-translate/useTranslation'

export const useTranslation = (defaultNs) => {
  const globalDefaultNs = 'translation'
  return useTranslationNext(defaultNs || globalDefaultNs)
}
```
```
// pages/index.js
import { useTranslation } from '../utils/translation'

export default function Index () {
  const { t } = useTranslation()

  return (
    <>
      <h1>{t('title')}</h1>
    <>
  )
}
```

This way I can set a global default namespace without lose the possibility to set a default namespace to specific page or component. And as a bonus, if I need to change to another library in the future, the work will be less.

**Comment by aralroca** [comment]
I think that right now it could be configured like this.

```js
{
  // ...rest of config
  "loadLocaleFrom": async (lang, ns) => {
     const ns = await import(`./locales/${lang}/${ns}.json`).then((m) => m.default)
     const defaultNS = await import(`./locales/${lang}/common.json`).then((m) => m.default)
     return { ...defaultNS, ...ns }
   }
}
```

**Comment by aralroca** [comment]
Already supported in new versions in `defaultNS` configuration https://github.com/aralroca/next-translate#3-configuration
