### ISSUE TITLE
Issue with Trans Component and next-link

### ISSUE THREAD

**Issue by timheerwagen** [aralroca/next-translate#840]
import Link from "next/link";

JSX:
```
 <Trans
      i18nKey="test"
      components={{
        link: <Link href="/" />,
        a: <a />,
      }}
/>
```

JSON:
```
"test": "stuff <link><a>more stuff</a></link>"
```

throws following error:
`Error: Multiple children were passed to <Link> with `href` of `/` but only one child is supported https://nextjs.org/docs/messages/link-multiple-children 
Open your browser's console to view the Component stack trace.`

**Comment by aralroca** [comment]
Try only one, `"test": "stuff <link>more stuff</link>"` with:

```jsx
<Link href="/" passHref>
  <a />
</Link>
```

**Comment by timheerwagen** [comment]
Without the <a> tag it works.
passHref has not changed anything

Solution:

```
 <Trans
      i18nKey="test"
      components={{
        link: <Link href="/" />,
      }}
/>
```
```
"test": "stuff <link><a>more stuff</a></link>"
```

**Comment by savayer** [comment]
But what if we want to add a className to the link?

```
"hello": "Hello <link>world</link>
```

```js
<TransText
  text={t('hello')}
  components={{
    link: (
      <Link href="/">
        <a className="link" />
      </Link>
    ),
  }}
/>
```

Result is `Hello <a href="/">world</a>`

**Comment by martinratinaud** [comment]
> But what if we want to add a className to the link?
> 
> ```
> "hello": "Hello <link>world</link>
> ```
> 
> ```js
> <TransText
>   text={t('hello')}
>   components={{
>     link: (
>       <Link href="/">
>         <a className="link" />
>       </Link>
>     ),
>   }}
> />
> ```
> 
> Result is `Hello <a href="/">world</a>`

Yes, same problem for me here

**Comment by NicoloPano** [comment]
> But what if we want to add a className to the link?
> 
> ```
> "hello": "Hello <link>world</link>
> ```
> 
> ```js
> <TransText
>   text={t('hello')}
>   components={{
>     link: (
>       <Link href="/">
>         <a className="link" />
>       </Link>
>     ),
>   }}
> />
> ```
> 
> Result is `Hello <a href="/">world</a>`

Well, i found a workaround for this case, i did it because i was in the same situation and i needed a solution immediately
I know it's not the kind of solution someone would like to implement but it works:
```
const TransLink: FC<PropsWithChildren<{ href: string; className?: string }>> = ({ href, className, children }) => (
    <>
        {React.Children.toArray(children).map((children, i) => (
          <Link key={`translink-${i}`} href={href} passHref>
              <a className={className}>{children}</a>
          </Link>
        ))}
    </>
)

export default TransLink
```
And then it can be used like you normally would use a `<Link />` component like so:
```
<TransText
    text={t('hello')}
    components={{
        link: <TransLink href="/" className="link" />,
    }}
/>
```

Result is `Hello <a href="/" class="link">world</a>`

**Comment by NicoloPano** [comment]
> @NicoloPano Since Next 13, you no longer need an anchor tag as the child of a link, as a link now works like an anchor.

Yep, but for some project requirement i need to use Next 12 so i posted my "solution" in case someone needs it :)

**Comment by aralroca** [comment]
Probably is this issue already fixed in Next.js 13?

**Comment by NicoloPano** [comment]
@aralroca Since Next.js 13 compile Link components to <a /> tags it's fixed.
However for Next.js 13 Links with legacyBehavior or Next.js 12 (or minor versions) a solution like mine above can be used
