### ISSUE TITLE
How to prevent returning the key name for missing keys?

### ISSUE THREAD

**Issue by geryit** [aralroca/next-translate#846]
Eg: `t("hello {{name}}", {name: "Jake"})` is printed as `hello {{name}}` if `hello {{name}}` key is missing

When I do `t("hello {{name}}", {name: "Jake"}, {default: "hello {{name}}" })`, its printed as `hello Jake`

**Comment by aralroca** [comment]
Check the `allowEmptyStrings` in the configuration: https://github.com/aralroca/next-translate#3-configuration

And check `fallbacks`: https://github.com/aralroca/next-translate#8-fallbacks

**Comment by aralroca** [comment]
This is because the `default` is the `value`, not the `key`. Interpolation is not implemented in keys, only in the value. And if doesn't have value by default is returning the key, but without doing interpolation... If you are interested in this, feel free to PR this change:

https://github.com/aralroca/next-translate/blob/e3f44c0926990e776b6b1e50bbbf71a6713ac0ab/src/transCore.tsx#L85-L86

**Comment by geryit** [comment]
We can close this @aralroca . We found a solution.

**Comment by aralroca** [comment]
Ohh cool! Share here the solution if others have the same problem. Thanks 😊

**Comment by geryit** [comment]
We override `i18n.t`

```
import i18n from "i18next";
import {I18n, Translate} from "next-translate";
import setLanguage from "next-translate/setLanguage";
import TransText from "next-translate/TransText";
import nextUseTranslation from "next-translate/useTranslation";
import {useMemo} from "react";

import {I18nNamespace} from "./i18n-namespaces";
import Trans from "./Trans";

type TranslateOptions = Parameters<I18n["t"]>[2];
type I18nKey = Parameters<I18n["t"]>[0];

const addDefaultToOptions = (options: TranslateOptions, i18nKey: I18nKey) => ({
  ...options,
  default: options?.default || (typeof i18nKey === "string" && i18nKey) || undefined,
});

const fixInterpolation =
  (t: Translate): Translate =>
  (i18nKey, query, options) =>
    t(i18nKey, query, addDefaultToOptions(options, i18nKey));

// When translating new text, make sure to update the translations too:
// https://mdcollab.atlassian.net/wiki/spaces/engineering/pages/680329381/Localization
const useTranslation = (namespace?: I18nNamespace): I18n => {
  const i18nWithBadInterpolation = nextUseTranslation(namespace);

  return useMemo<I18n>(
    () => ({
      t: fixInterpolation(i18nWithBadInterpolation.t),
      lang: i18nWithBadInterpolation.lang,
    }),
    [i18nWithBadInterpolation],
  );
};

export {i18n, useTranslation, Trans, TransText, setLanguage};
```
