### ISSUE TITLE
Missing security headers using next-translate

### ISSUE THREAD

**Issue by marcogianni** [aralroca/next-translate#848]
Hi, using next-translate seems to ignore the headers. I have this configuration in `next.config.js`. Am I doing something wrong?

```javascript
const nextTranslate = require('next-translate')

const securityHeaders = [
  {
    key: "X-XSS-Protection",
    value: "1; mode=block",
  },
  {
    key: "X-DNS-Prefetch-Control",
    value: "on",
  },
  {
    key: "X-Frame-Options",
    value: "SAMEORIGIN",
  },
  {
    key: "X-Content-Type-Options",
    value: "nosniff",
  },
];

module.exports = withBundleAnalyzer(
  nextTranslate({
    async headers() {
      return [
        {
          source: "/(.*)", // Apply these headers to all routes in your application.
          headers: securityHeaders,
        },
      ];
    },
    reactStrictMode: true,
    poweredByHeader: false,
  })
);
```

```
"next": "12.1.1",
"next-translate": "^1.3.5",
```

**Comment by marcogianni** [comment]
I also tried this configuration but nothing: 
https://github.com/vinissimus/next-translate/issues/708

**Comment by aralroca** [comment]
All Next-translate does is pass the configuration you pass to Next.js. It doesn't touch anything... 

Line 50, defined on line 3
https://github.com/vinissimus/next-translate/blob/49f580c6d292712a0720a104de3b487e7c11d4ae/src/plugin/index.ts#L49-L56

The whole i18n routing also uses the Next.js core. 

If you use [Next.js i18n routing](https://nextjs.org/docs/advanced-features/i18n-routing) directly without Next-translate is working? Maybe this issue should be reported to [Next.js repository](https://github.com/vercel/next.js/issues).

**Comment by marcogianni** [comment]
I'm sorry, next-translate works. 
I solved placing i18n object inside module.export in next.config.js (and not or project root) and adding this for all language:
```
      {
        source: '/de',
        locale: false,
        headers: securityHeaders,
      },
```
 https://nextjs.org/docs/api-reference/next.config.js/headers#headers-with-i18n-support

Using only `source: "/(.*)"` was not enough.
