### ISSUE TITLE
Incorrect `pages` folder detection

### ISSUE THREAD

**Issue by finkrer** [aralroca/next-translate#853]
https://github.com/vinissimus/next-translate/blob/49f580c6d292712a0720a104de3b487e7c11d4ae/src/plugin/index.ts#L27-L36

As you can see, the root `pages` directory is not chosen if `src/pages` exists.

However, Next.js has it [the other way around](https://nextjs.org/docs/advanced-features/src-directory):

> `src/pages` will be ignored if `pages` is present in the root directory

As a result, `next-translate` does not work with such folder structure.

**Comment by aralroca** [comment]
This should be fixed in 2.0.0-canary.3
