### ISSUE TITLE
Page.getInitialProps not called

### ISSUE THREAD

**Issue by hyze2d** [aralroca/next-translate#865]
Getinitialprops is not being called when next-translate configured
I tried with getServerSideProps and getStaticProps and it works fine but for some reason Page.getInitialProps which i define is not being called at all. Am i missing something?

Even with simple setup like that it reproduces for me

![image](https://user-images.githubusercontent.com/37380296/173961716-2e6417f2-ded6-4f5d-b12c-e60a8412eab4.png)

GIP works if i disable next-translate so i do think it's related. Am i missing something maybe?

**Comment by aralroca** [comment]
Probably related with this issue? https://github.com/vinissimus/next-translate/issues/486

**Comment by aralroca** [comment]
It should be solved in Next-translate 2.0.0-canary.3 

I'm going yo close the issue. Feel free to comment here if the problem stills here, but we replaced all regex to a parser to fix all this kind of problems.
