### ISSUE TITLE
Invalid next.config.js options detected

### ISSUE THREAD

**Issue by dakshinasd** [aralroca/next-translate#887]
`next-translate`: 1.5.0
`next`: 12.2.3

i18n.js
```
const hoistNonReactStatics = require('hoist-non-react-statics');

module.exports = {
  locales: ['en', 'nl'],
  defaultLocale: 'en',
  pages: {
    '*': ['common'],
  },
  loadLocaleFrom: async (lang) => {
    const commonTranslations = await import('translations');
    const appTranslations = await import('./src/translations/');

    return new Promise((resolve) =>
      resolve({ ...commonTranslations[lang], ...appTranslations[lang] })
    );
  },
  defaultNS: 'common',
  staticsHoc: hoistNonReactStatics, // required for loading custom layouts with translations
};
```

next.config.js
```
/** @type {import('next').NextConfig} */

const nextTranslate = require('next-translate');
const withTM = require('next-transpile-modules')([
  'components',
  'hooks',
]);

const nextConfig = {
  reactStrictMode: true,
};


module.exports = withTM(nextTranslate(nextConfig));

```

Whenever I run my app, I get following warning on my console. How can I fix this?
```
warn  - Invalid next.config.js options detected: 
[
  {
    "instancePath": "/i18n",
    "schemaPath": "#/properties/i18n/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "loadLocaleFrom"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "/i18n",
    "schemaPath": "#/properties/i18n/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "defaultNS"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "/i18n",
    "schemaPath": "#/properties/i18n/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "staticsHoc"
    },
    "message": "must NOT have additional properties"
  }
] 
```

Is there something wrong with how I have configured things?

**Comment by Dragate** [comment]
> Is there something wrong with how I have configured things?

No. Next.js has started validating `next.config` with `ajv`. Currently, `next-translate` is injecting irrelevant information to Next.js (apart from `locales` and `defaultLocale`), which tiggers this warning.

Culprit:
https://github.com/vinissimus/next-translate/blob/7ebba0c71362b2dd349472d854730c098c793152/src/plugin/index.ts#L53

**Comment by geryit** [comment]
Seeing the same working on nextjs v12.2.3

**Comment by dakshinasd** [comment]
@Dragate Thanks for the explanation. Is there a way that I can get rid of this or should I need to wait until a fix is published for `next-translate`?

**Comment by irhamputra** [comment]
is any update or solution from this issue? i also get the same issue here

**Comment by tuncatakan** [comment]
Same problem... 

My i18n.json : 

`{
  "locales": ["en", "tr"],
  "defaultLocale": "tr",
  "pages": {
    "*": ["common"]
  },
  "logBuild": false,
  "localeDetection": false
}
`

And I get this error

`warn  - Invalid next.config.js options detected: 
[
  {
    "instancePath": "/i18n",
    "schemaPath": "#/properties/i18n/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "logBuild"
    },
    "message": "must NOT have additional properties"
  }
] `

When i remove logBuild:false line in next.config.js error is gone!

**Comment by irhamputra** [comment]
@tuncatakan yes it's because Next.js config didn't support those additionalProperties from next-translate.

**Comment by tuncatakan** [comment]
> @tuncatakan yes it's because Next.js config didn't support those additionalProperties from next-translate.

Yes, I understand the situation. @Dragate said that he started using the new ajv validation.  I guess we will wait for the new version to be released for this error to be fixed.

**Comment by IRediTOTO** [comment]
I get this error too

**Comment by aralroca** [comment]
It can be solved instead of `...restI18n` https://github.com/aralroca/next-translate/blob/master/src/plugin/index.ts#L53, just add all i18n options from Next.js... PRs are welcome!! Thanks :)

**Comment by radum** [comment]
I am looking to raise a PR but in the mean time, this is a warning, will it affect the functionality of this module in any way?

**Comment by aralroca** [comment]
Even if it is a warning if it is fixed it will be very welcome. It will not grow the size of the library because it is the plugin part of webpack.

**Comment by matiasfacio** [comment]
I have this problem as well. This is the code: 
`module.exports = nextTranslate(
  withPWA({
    output: "standalone",
    productionBrowserSourceMaps: true,
    optimizeFonts: false,
    pwa: {
      disable: process.env.NEXT_PUBLIC_DEBUG === "true",
      mode: process.env.NEXT_PUBLIC_DEBUG === "true" ? "development" : "production",
      dest: "public",
      runtimeCaching: cache,
    },
    webpack: (config) => {
      config.module.rules.push({
        test: /\.ttf$/i,
        type: "asset/resource",
      });
      return config;
    },
    logBuild: false,
    loadLocaleFrom: (lang, ns) =>
      new Promise(async (resolve, reject) => {
        const res = await import(`./locales/${lang}/${ns}.json`).then(
          (m) => m.default,
          // If there's no file for chosen language, use "en".
          async (reason) => {
            const fallbackRes = await import(`./locales/en/${ns}.json`).then((m) => m.default);
            if (fallbackRes) {
              resolve(fallbackRes);
            } else {
              reject();
            }
          },
        );
        resolve(res);
      }),
  }),
);`

I had to move both logBuild and loadLocaleFrom inside the config file, in order for the next.js to compile, otherwise, I would get: 

`./i18n.js Critical dependency: the request of a dependency is an expression`

Am I doing something wrong here? Any help will be very much appreciated 🙏🏻

**Comment by aralroca** [comment]
> I had to move both logBuild and loadLocaleFrom inside the config file, in order for the next.js to compile, otherwise, I would get:
> 
> `./i18n.js Critical dependency: the request of a dependency is an expression`
> 
> Am I doing something wrong here? Any help will be very much appreciated 🙏🏻

I think is related to this issue about dynamic import and SWC: https://github.com/aralroca/next-translate/issues/851. At the moment we don't know how to fix it yet, but there is a temporal workaround to fix it https://github.com/aralroca/next-translate/issues/851#issuecomment-1173611946 (without using `require`, that increase the bundle size)

**Comment by aralroca** [comment]
I'm going to close this issue. It should be already solved in:

Next-translate 2.0.0-canary.3
Next.js 13.1.7-canary.11
