### ISSUE TITLE
Issue with next lint

### ISSUE THREAD

**Issue by sigurdarson** [aralroca/next-translate#896]
I have an issue with the Trans component as running `yarn lint` with strict rules (`"extends": "next/core-web-vitals"`) cause me to get this error: `Error: Missing "key" prop for element in array  react/jsx-key`

Trans component
```
     <Trans
           i18nKey='case:introDescription'
           components={[<Component />, <br />]}
           values={{ partner: data.partnerName }}
      />
```

**Comment by aralroca** [comment]
This is not a next-translate issue, is about React arrays of elements. You can add a `key`:

```js
[<Component key="0" />, <br key="1" />]
````

if there are different components there is no issue, but React needs the key if there is a repeated component.

```js
[<Component />, <br  />, <Component  /> /* Bug with duplicate component */]
````

https://reactjs.org/docs/lists-and-keys.html
