### ISSUE TITLE
defaultLocale Not workink

### ISSUE THREAD

**Issue by OmarioHassan** [aralroca/next-translate#903]
**What version of this package are you using?**
"next": "12.2.5",
 "next-translate": "^1.5.0",
 "react": "18.2.0",
 "react-dom": "18.2.0"
**What operating system, Node.js, and npm version?**
Node v14.17.5
npm 6.14.14
**What happened?**
English is forced to be loaded as a default language

![image](https://user-images.githubusercontent.com/8146344/187075814-f62c0bb2-3aca-486a-bd12-57afff257a8f.png)

![image](https://user-images.githubusercontent.com/8146344/187075821-aa2dfbc7-d0bb-4dac-bfae-c5add3c907ee.png)

**What did you expect to happen?**
I'm expecting Arabic to be loaded as the default
**Are you willing to submit a pull request to fix this bug?**
No

**Comment by aralroca** [comment]
Maybe is for automatic location detection https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale

you can turn off with `localeDetection: false`. 

Can you confirm that is for this? Thanks!

**Comment by OmarioHassan** [comment]
@aralroca Yes, adding this solved the problem

![image](https://user-images.githubusercontent.com/8146344/187264971-c10cc979-e717-48bf-8860-8d5862ff8a80.png)

**Comment by aralroca** [comment]
Cool!! In this case, I'm going to close the issue!
