### ISSUE TITLE
Migrating to from Next 12.1.5 -> 12.2.5, Jest in Github Actions fails with Error: Cannot find module i18

### ISSUE THREAD

**Issue by dasblitz** [aralroca/next-translate#909]
**What version of this package are you using?**

1.5.0

**What operating system, Node.js, and npm version?**

OS: Ubuntu 20.04.5 LTS

node: 16.16.0
yarn: 1.22.19
next: 12.2.5
jest: 27.5.1.

**What happened?**

It's a bit of a complicated bug to reproduce as it only happens on github. I'm not sure if it's because of `jest`, `next`, `next-translate` or something weird in github actions. When I run my jest locally my tests work as expected. But in Github Actions I get the following error:

```terminal
Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error

 >  NX   Jest: Failed to parse the TypeScript config file /home/runner/work/mono-repo/mono-repo/apps/configurator/jest.config.ts

     Error: Cannot find module '/home/runner/work/mono-repo/mono-repo/i18'
     
   Require stack:
   - /home/runner/work/mono-repo/mono-repo/node_modules/next-translate/lib/cjs/plugin/index.js
   - /home/runner/work/mono-repo/mono-repo/node_modules/next-translate/lib/cjs/index.js
   - /home/runner/work/mono-repo/mono-repo/apps/configurator/next.config.js
```

**What did you expect to happen?**

I expected the path for the i18 module to be correct and have no errors during the parsing of the jest.config.ts file

**Are you willing to submit a pull request to fix this bug?**

I'd first like to have some help in understanding the actual problem, it seems like a conflicting cjs module resolver

**Comment by aralroca** [comment]
try to set [`NEXT_TRANSLATE_PATH`](https://github.com/aralroca/next-translate#13-how-to-use-next-translate-in-a-mono-repo)

**Comment by dasblitz** [comment]
Ah that was it! I still don't understand why it was working with the older versions of the mentioned packages though, but I'll take it, thanks 😄
