### ISSUE TITLE
AWS Amplify Error deploy with next.config file

### ISSUE THREAD

**Issue by DavidRojas1612** [aralroca/next-translate#910]
**What happened?**
I had having a error with my deploys. 

![image](https://user-images.githubusercontent.com/21252506/190196591-8c35d9c9-9e62-42a9-8171-ea8cea465cc5.png)

this is my file next-config.
![image](https://user-images.githubusercontent.com/21252506/190196888-c9ee49e5-d32d-42f0-a8a6-00c2c5e868dc.png)

**Comment by aralroca** [comment]
Are you sure is an issue from this library? It looks related to this one https://github.com/serverless-nextjs/serverless-next.js/issues/2477#issue-1337802242

**Comment by aralroca** [comment]
@DavidRojas1612 any new about this error? I'm going to close the issue because looks not related with next-translate. Feels free to comment if finally is related and I will re-open it. Thanks
