### ISSUE TITLE
SSR called on every page change with getInitialProps

### ISSUE THREAD

**Issue by DonovanCharpin** [aralroca/next-translate#911]
**What version of this package are you using?**
v1.5.0

**What operating system, Node.js, and npm version?**
Node v16.13.2, Next v12.1.6 (tried v12.3.0 too)

**What happened?**
After building the nextjs app, when navigating between routes (even static ones), the ssr is always called and does a refresh on the front. My _app is using getInitialProps. 
```
next-translate - compiled page: /integrations/integrations - locale: en - namespaces: common - used loader: getInitialProps
```

My current configuration : 
```
module.exports = {
  locales: ["en", "fr"],
  defaultLocale: "en",
  pages: {
    "*": ["common"],
  },
  keySeparator: false,
  nsSeparator: false,
  defaultNS: "common",
};
```

I'm not using any provider, just the basic config in next.config.js. If I remove the nextTranslate from next.config.js, it change the route only on the client side.

**What did you expect to happen?**
The compilation is called only on the first render, then the client handle the translation.

**Comment by aralroca** [comment]
@DonovanCharpin would you add a repo with an example that reproduces the error? Thanks!

**Comment by DonovanCharpin** [comment]
Hey @aralroca! Let me try to do that!

**Comment by sebastien-comeau** [comment]
I had this issue before and out of sudden it's gone but now I have `/status` page using `getServerSideProps` render method which is wrong. `/status` page render method should be `getStaticProps`. No render method is defined except for `_error.tsx`.

Here's the code base: https://github.com/DTS-STN/passport-status/commit/15f271dae4eeddc7e9eeaff169c3f1d65af1864f

```shell
info  - Collecting page data  
[    ] info  - Generating static pages (0/6)next-translate - compiled page: / - locale: en - namespaces: common - used loader: getStaticProps
next-translate - compiled page: /404 - locale: en - namespaces: common - used loader: getStaticProps
next-translate - compiled page: / - locale: fr - namespaces: common - used loader: getStaticProps
next-translate - compiled page: /landing - locale: fr - namespaces: common, landing - used loader: getStaticProps
next-translate - compiled page: /404 - locale: fr - namespaces: common - used loader: getStaticProps
next-translate - compiled page: /landing - locale: en - namespaces: common, landing - used loader: getStaticProps
info  - Generating static pages (6/6)
info  - Finalizing page optimization

Route (pages)                              Size     First Load JS
┌ ● /                                      5.22 kB         103 kB
├   /_app                                  0 B              95 kB
├ ○ /404                                   897 B          98.2 kB
├ λ /api/check-status                      0 B              95 kB
├ ● /landing                               2.29 kB        99.6 kB
└ λ /status                                36.9 kB         134 kB
+ First Load JS shared by all              98.9 kB
  ├ chunks/framework-8fe61cd0cc2cc9de.js   45.3 kB
  ├ chunks/main-d04d9ca8f793c3a4.js        35.7 kB
  ├ chunks/pages/_app-66b62a2f8a5c3f73.js  12.1 kB
  ├ chunks/webpack-a1bb4252a02ea680.js     1.94 kB
  └ css/5a2a76468de5f028.css               3.9 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
```

**Comment by aralroca** [comment]
@DonovanCharpin If I cannot reproduce the issue it is very difficult for me to help. The only case that comes to my mind that can happen to  SSR on all pages, is that a HOC is being used in the _app.js.

Explained here this use case: https://github.com/aralroca/next-translate#how-are-translations-loaded

If is this the problem, should be solved in  [2.0.0-experimental.2](https://github.com/aralroca/next-translate/releases/tag/2.0.0-experimental.2). Can you confirm and give feedback about the comming 2.0 version?  Thank you so much!

**Comment by DonovanCharpin** [comment]
Thanks for your reply @aralroca !

Unfortunately the `v2.0.0` does not fix it. The issue really comes whenever I click on a link, I see directly the front calling the back as if I was using `getServerSideProps`. Even if I see from the log that the loader is `getInitialProps` when generating the page.

If I remove the plugin `nextTranslate` in the next.config.js, the links work as expected (no more backend call). I have a custom server but it does not do much so I don't think that it is the issue.

I have a main `_app.js` like this
``` js
class MyApp extends App {
  static getInitialProps = wrapper.getInitialAppProps(((store) =>
      async ({ Component, router, ctx }) => { ... ))
  ));
  
  render() {
    const { router, ...templateProps } = this.props;

    return (
      ...
    
      <ReactReduxContext.Consumer>
        {({ store }) => (
          <PersistGate persistor={store.__persistor}>
            <MainApp {...templateProps} />
          </PersistGate>
        )}
      </ReactReduxContext.Consumer>
    );
  }
}

const enhance = compose(wrapper.withRedux);

export default enhance(MyApp);
```

**Comment by aralroca** [comment]
Is for the HOC in _app.js, is doing by default getInitialProps to avoid conflicts with libraries that are adding the getInitialProps in their HOC.

Related with this issue https://github.com/aralroca/next-translate/issues/584

To avoid this default you can add an empty loader on _app.js: https://github.com/aralroca/next-translate/issues/801#issuecomment-1059800473

**Comment by DonovanCharpin** [comment]
I tried both of the links but it does not work for me.

I have only one `_app.js` which implements `getInitialProps`. The page should be generated only on the first load, then the bundle is loaded and the navigation is handled by the client (without calling the backend).

I really want to keep this behaviour with `getInitialProps`. `next-translate` seems to understand that because all the pages are generated with getInitialProps as loader.
``` sh
next-translate - compiled page: /building-guide - locale: en - namespaces: common - used loader: getInitialProps
```

The issue is if I click on a next Link or even if I use Router.pushRoute("..."), it does a round trip to the backend to translate the page and reload the entire page to the new route. I don't know if it can be linked to the `custom server` or `next-routes` but the issue appears only when the `next-translate` plugin is added to the next.config.js, as if it was converting my page to a `getServerSideProps`.

**Comment by DonovanCharpin** [comment]
Follow-up on this issue. It seems that it was linked to next-routes and express, I removed both from the app and now it works!
