### ISSUE TITLE
use next-translate in javascript

### ISSUE THREAD

**Issue by lynn1286** [aralroca/next-translate#927]
**What version of this package are you using?**
` "next-translate": "^1.6.0"`

**What problem do you want to solve?**
How to use next - translate outside of components, for example:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/40122311/191734392-59ea7cbd-2907-4fc5-99e1-d98fc6b40c81.png">

**What do you think is the correct solution to this problem?**
Hope to provide the same capabilities as next - i18next ， for example: 
<img width="735" alt="image" src="https://user-images.githubusercontent.com/40122311/191734684-015e0c5c-293c-474a-a356-02d2f6890f00.png">

**Comment by aralroca** [comment]
You can do it with `getT`: https://github.com/aralroca/next-translate#gett is asynchronous because if you don't have the namespace it will download it.
