### ISSUE TITLE
False error about missing translation keys.

### ISSUE THREAD

**Issue by sawa-ko** [aralroca/next-translate#929]
**What version of this package are you using?**
1.6.0

**What operating system, Node.js, and npm version?**
OS: Windows 11
Node: v18.6.0
NPM: 8.13.2
Next: 12.3.0

**What happened?**
When I start the development server, I usually get this error: `[next-translate] "layout:header.menu.home" is missing in current namespace configuration. Try adding "header.menu.home" to the namespace "layout"`.

And despite the error saying that the translation key does not exist, the component is displayed correctly on the web.

Any way to fix it?

```
// nextjs.config.js
const nextTranslate = require('next-translate');
const withBundleAnalyzer = require('@next/bundle-analyzer')({
	enabled: process.env.ANALYZE === 'true'
});

/** @type {import('next').NextConfig} */
const nextConfig = {
	reactStrictMode: true,
	swcMinify: true
};

module.exports = nextTranslate(withBundleAnalyzer(nextConfig));

// component
const { t } = useTranslation('layout');


<Stack spacing={4} direction="row" align="center" display={{ base: 'none', lg: 'flex' }}>
	<NextLink href={'/'} passHref>
		<Button as="a" size="sm" variant={router.pathname === '/' ? 'solid' : 'ghost'} leftIcon={<Icon name="home" />}>
			{t`header.menu.home`}
		</Button>
	</NextLink>
	<Button size="sm" variant={router.pathname === '/commands' ? 'solid' : 'ghost'} disabled leftIcon={<Icon name="code" />}>
		{t`header.menu.commands`}
	</Button>
	<Button size="sm" variant={router.pathname === '/stats' ? 'solid' : 'ghost'} disabled leftIcon={<Icon name="chart-area" />}>
		{t`header.menu.stats`}
	</Button>
</Stack>
```

![image](https://user-images.githubusercontent.com/56084970/191788440-bcfa0dbf-7ab8-40da-8303-bf9bfc3587fc.png)

![image](https://user-images.githubusercontent.com/56084970/191788549-0df31220-e39f-4862-8890-7da73d24cddb.png)

![image](https://user-images.githubusercontent.com/56084970/191788721-36a1455c-b065-4b42-bd7e-4403b5e405c6.png)

**What did you expect to happen?**
When I start the development server, I usually get this error: [next-translate] "layout:header.menu.home" is missing in current namespace configuration. Try adding "header.menu.home" to the namespace "layout".

And despite the error saying that the translation key does not exist, the component is displayed correctly on the web.

Any way to fix it?

**Are you willing to submit a pull request to fix this bug?**
Idk.

**Comment by aralroca** [comment]
Would you share your `i18n.json` file? Thanks!

**Comment by kaname-png** [comment]
Hi @aralroca sure, this is my file `i18n.json`
```javascript
// @ts-check
/** @type {import('next-translate').I18nConfig} */
module.exports = {
	locales: ['__default', 'es-ES', 'en-US'],
	defaultLocale: '__default',
	localesToIgnore: ['__default'],
	pages: {
		'*': ['common', 'layout'],
		'/': ['home'],
		'/privacy': ['privacy-policy'],
		'/tos': ['terms-condition'],
		'/404': ['error'],
		'/500': ['error'],
		'/_error': ['error']
	},
	loggerEnvironment: 'node',
	defaultNS: 'common'
};
```

**Comment by aralroca** [comment]
It might have to do with the `_default`... Just to verify, if you change the `defaultLocale` to `es-ES` is also displaying this warning? it is probable that there is a moment in the build that does not have the right language and tries to search inside `locales/_default` and that is why the warning comes out...  Thanks

**Comment by kaname-png** [comment]
Yes, the error occurs setting the default language as either __default or es-ES.

**Comment by kaname-png** [comment]
@aralroca I just figured out when the error happens.

The error occurs when this warning appears, and I started to inspect the next-translate code, and when this message appears in the `transCore` method, `allNamespaces` appears as an empty `object`.

![image](https://user-images.githubusercontent.com/56084970/192200124-5b25922a-b970-49bb-af3f-11fe082cea05.png)

**Comment by Adriangar99** [comment]
Same error here with version 1.6.0
