### ISSUE TITLE
Support for Next.js v12.3 fallbackNodePolyfills

### ISSUE THREAD

**Issue by christoph-pflueger** [aralroca/next-translate#932]
**What version of this package are you using?**

1.6.0

**What operating system, Node.js, and npm version?**

Ubuntu 22.04.1 LTS, Node.js 16.16.0 & pnpm 7.12.2

**What happened?**

Next.js released an experimental configuration option `fallbackNodePolyfills` in v12.3. Setting it to `false` breaks `next-translate` as it requires `NODE_DISABLE_COLORS` on the client.

**What did you expect to happen?**

`next-translate` not to require `NODE_DISABLE_COLORS` on the client.

**Are you willing to submit a pull request to fix this bug?**

Not at the moment.

**Comment by aralroca** [comment]
Fixed in [2.0.2](https://github.com/aralroca/next-translate/releases/tag/2.0.2) to only run in server-side. Can you verify if is working fine now @christoph-pflueger ? Thanks
