### ISSUE TITLE
Support for next.js v13

### ISSUE THREAD

**Issue by kaname-png** [aralroca/next-translate#938]
**What version of this package are you using?**
2.0.0-experimental.3

**What problem do you want to solve?**
Now next.js officially implemented the "app" folder, which has many new features for the nextjs router and pages (https://nextjs.org/blog/next-13).

Currently next-translate doesn't look for pages in the "app" folder and (in my case) when I try to compile, the nextjs compiler gets stuck using next-translate.

**What do you think is the correct solution to this problem?**
Allow compatibility with nextjs v13.

**Are you willing to submit a pull request to implement this change?**
I don't know.

**Comment by aralroca** [comment]
There are some things to consider:

- You currently can change the `pages` folder to `app` using `pagesInDir` in the configuration: https://github.com/aralroca/next-translate/tree/canary#3-configuration However, in the new layouts they replace the `getStaticProps` and `getServerSideProps` to `fetch`... This is not supported yet in the Next-translate Webpack plugin, but you can use the `getT` method to load the namespaces you need in each page.
- It's also in alpha replacing Webpack to Turbopack... In this point our Webpack plugin is going to be irrelevant.
- Next.js 13 should work well with `pages`, to use this `app` for the layouts you need to activate an experimental flag, and everything is in beta and may can change.

As the beta progresses, if so, I would look for an alternative to the Webpack plugin, to make it more efficient. I think spending energy to make the Webpack plugin work 100% well for layouts would be something that may soon change completely with Turbopack.

The ideal would be to focus version 2.0.0 of Next-translate to support layouts in a different way (without Webpack plugin), but easy, simple and fast.

**Comment by aralroca** [comment]
I close the issue because looks that is working fine with Next.js 13

**Comment by kaname-png** [comment]
@aralroca 

```tsx
// ../components/i18n.tsx
'use client';

import I18nProvider from 'next-translate/I18nProvider';
export default I18nProvider;
```

```tsx
// app/layout.tsx
import I18nProvider from '@/components/shared/chakra/i18n';

import Footer from '@/components/shared/footer';
import NavBar from '@/components/shared/navbar';

import commonEn from '../locales/common.json';

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en-US">
			<head />
			<body>
				<I18nProvider lang={'en-US'} namespaces={{ commonEn }}>
						<NavBar />
						{children}
						<Footer />
				</I18nProvider>
			</body>
		</html>
	);
}
```

```tsx
export default async function Page() {
	const lang = await getT('en-US');
	return <h1>{lang('app_name')}</h1>
}
```

![image](https://user-images.githubusercontent.com/56084970/204612033-8a0e8cbd-52c1-4b25-9df6-32fe597d9e25.png)

**Comment by awinogrodzki** [comment]
@aralroca is there any specific configuration that allows to run `next-translate` against Next.js 13? I cannot get it to work with following config:

```js
// next.config.js
const nextTranslate = require('next-translate');

/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
    allowMiddlewareResponseBody: true,
  }
};

module.exports = nextTranslate(nextConfig);
```

```js
// i18n.js
module.exports = {
  locales: ['en', 'pl'],
  defaultLocale: 'en',
  defaultNS: 'dashboard',
  pages: {
    '*': ['dashboard'],
  },
};
```

```json
// locales/en/dashboard.json
{
  "save": "Save",
  "clientId": "Client ID",
  "clientIdTooltip": "Should contain lowercase a-z characters optionally separated by dash (\"-\") character"
}
```

Using following code in `app/**/page.tsx` does not seem to be working
```jsx
 const { t } = useTranslation();
 ...
 t('clientId'); // returns "clientId"
 t('save');  // returns "save"
 t('clientIdTooltip');  // returns "clientIdTooltip"
```

**Comment by cotwitch** [comment]
> I close the issue because looks that is working fine with Next.js 13

Did you mind about adding example ( Next.js 13 using `app directory` feature ) in docs?

**Comment by aralroca** [comment]
app-dir is now already supported in 2.0.0-canary.3 😊😊
