### ISSUE TITLE
Is there a way to pack the language files into a file for caching instead of writing them in __NEXTDATA__ in each html file

### ISSUE THREAD

**Issue by weee-joseph** [aralroca/next-translate#939]
__NEXTDATA__ is full of namespaces. Many pages require less language configuration, but are packed into each page.

**Comment by aralroca** [comment]
More info please. The namespaces are loading for each page but only the namespaces that the page needs

**Comment by weee-joseph** [comment]
> 

For example,  I didn't use any language key in a page, but this page loads all the languages in the current namespace

**Comment by aralroca** [comment]
The logic of loading the namespaces does not depend on the Keys that are used, but on the namespaces that the page needs, and this is specified inside the configuration (i18n.js) in the property pages.

Example:

https://github.com/aralroca/next-translate/blob/c64916f3a42a3879e0bf94b393352da1cdbbc79d/examples/complex/i18n.js#L7-L10

The logic of adding it in Nextdata is internal to Next.js if the page wants to use something loaded in a loader (getStaticProps, etc). So no sorry, there is no alternative, that's how Next.js works 😅
