### ISSUE TITLE
Expose formatElements

### ISSUE THREAD

**Issue by testerez** [aralroca/next-translate#948]
**What version of this package are you using?**

next-translate@1.6.0

**What problem do you want to solve?**

I'm using `next-translate` to translate emails built with [Mailing](https://www.mailing.run/). Unfortunately, this does not allow me to user react context. This is why I rely on `getT` to provide a `Translate` function to my components.
It works well but I also need to translate texts including HTML tags. But unfortunately, `Trans` component relies on context so it does not work for me.

**What do you think is the correct solution to this problem?**

Either allow me to pass `Translate` function to `Trans` component so that it does not rely on `useTranslation`.
Or, simply expose `formatElements` so that I can use it directly.

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by aralroca** [comment]
Verify first if `next-translate/lib/esm/formatElements` or `next-translate/lib/cjs/formatElements` is solving this. After you verify it, we can do it public to be directly `next-translate/formatElements`

**Comment by testerez** [comment]
Thanks @aralroca , it does work for me with either esm of cjs. Thouhg Typescript definitions are missing.

**Comment by aralroca** [comment]
Feel free to PR to add the Typescript definitions, and to do it public you can add this file here: 

https://github.com/aralroca/next-translate/blob/master/package.json#L32

**Comment by testerez** [comment]
Thanks, I'll do it when I find the time 👍

**Comment by aralroca** [comment]
@testerez do you already need `formatElements`? Feel free to comment and I will re-open the issue
