### ISSUE TITLE
Add warning for cases when translation expected variable but none is passed

### ISSUE THREAD

**Issue by abriginets** [aralroca/next-translate#955]
**What version of this package are you using?**
1.6.0

**What problem do you want to solve?**
I want to get notified when I forgot to pass down a variable to namespace key that expects it. For example, I have the following translation JSON:
```json
{
  "meta": {
    "title": "Cheap flights",
    "description": "{{hostname}} looks up for cheap flight tickets through hundreds of agencies and dozens of airlines all accross the world to let travelers choose the cheapest ones"
  },
}
```
But in the code I actually forgot to pass down any value:
```ts
description={t('meta.description')}
```
which would render it "as is" on the page:
```html
<meta name="description" content="{{hostname}} looks up for cheap flight tickets through hundreds of agencies and dozens of airlines all accross the world to let travelers choose the cheapest ones"/>
```
and there is no way to know that it's missing. The only thing I can do is manually open page source code and look for `{{` occurences which is not the best thing to do considering all HTML is minified by Next even in dev environments.

**What do you think is the correct solution to this problem?**
Put warnings to the console with corresponding message. Allow to modify severity by choosing between `console.info`/`console.warn`/`console.error`\`console.log`;

**Are you willing to submit a pull request to implement this change?**
No

**Comment by aralroca** [comment]
Did you try the `logger` from the configuration?

<img width="848" alt="Screenshot 2022-12-13 at 12 30 51" src="https://user-images.githubusercontent.com/13313058/207306873-434ea4ce-c314-431c-92d8-0bcad6463cdf.png">



https://github.com/aralroca/next-translate#3-configuration
