### ISSUE TITLE
Typesafe Translation keys

### ISSUE THREAD

**Issue by timheerwagen** [aralroca/next-translate#959]
**What version of this package are you using?**
1.6.0

**What problem do you want to solve?**
I often forget to add translation keys that I add to a page to my locales as well. Or to keep the files consistent between different languages. This would make creating new pages and components easier and save some testing. Using .ts locale files already works fine.

**What do you think is the correct solution to this problem?**
Typsafe Keys. I guess it would be enough to pass the type to useTranslation

**Example:** 

```
type BlogPostTranslation = {
  title: string;
  description: string
}
```

```
const blogPostLocales: BlogPostTranslation = {
  title: "Titel",
  description: "Beschreibung",
}
```

```
export const BlogPost = () => {
  const { t } = useTranslation<BlogPostTranslation>("blogPost")

  return <div>
    <p>{t("title")}</p>
    <p>{t("description")}</p>

    {/* <p>{t("content")}</p> // content not found in BlogPostTranslation */}
  </div>
}
```

**Comment by cassus** [comment]
Related: https://github.com/aralroca/next-translate/issues/721

**Comment by aralroca** [comment]
I close as duplicated of https://github.com/aralroca/next-translate/issues/721
