### ISSUE TITLE
Fix invalid support info

### ISSUE THREAD

**Issue by voxpelli** [aralroca/next-translate#963]
Your `.github` repository is a fork of the StandardJS one and still contains mentions of eg our Discord channel: https://github.com/aralroca/.github/blob/c56790c5265d6cce126213d04d9568d280a89c11/.github/ISSUE_TEMPLATE/config.yml#L4

Please correct this and other unchanged info instead of eg. sending confused users to our Discord asking for help there 🙏

Similar to https://github.com/maggie0002/balena-plex-seedbox/issues/3

**Comment by aralroca** [comment]
Thanks, updated! 😊
