### ISSUE TITLE
__namespaces is not working on getStaticProps

### ISSUE THREAD

**Issue by siamak** [aralroca/next-translate#970]
**What version of this package are you using?**
`"next-translate": "^1.6.0"`
**What operating system, Node.js, and npm version?**
`v16.15.1`
**What happened?**
I'm passing my custom translations (retrieve from Server) on `getStaticProps`:

```
return {
    props: {
        ...,
        __lang: "fr",
        __namespaces: {
            common: {...}
        }
    }
}
```

But `next-translate` is not working and doesn't integrate with these translations.

**Comment by aralroca** [comment]
To fix this is necessary to move this line:

https://github.com/aralroca/next-translate/blob/fc429c7094fdcd459d87cc7405a359a006d28cb2/src/plugin/templateWithLoader.ts#L37

Below the `loadNamespaces`. Feel free to do a PR to fix this.

**Comment by siamak** [comment]
I just wanted to do a PR to fix this but I couldn't find the problem. If you can give me some hints. I'll do a PR for this.

**Comment by aralroca** [comment]
It should be fixed by moving this line 37 https://github.com/aralroca/next-translate/blob/fc429c7094fdcd459d87cc7405a359a006d28cb2/src/plugin/templateWithLoader.ts#L37 to line 45, just be fine to don't be overwritten. However, would be interesting to write first the failing test before this.
