### ISSUE TITLE
Rewrites to /api are broken

### ISSUE THREAD

**Issue by abriginets** [aralroca/next-translate#974]
**What version of this package are you using?**

1.6.0

**What operating system, Node.js, and npm version?**

Ubuntu 20.04, NodeJS 18.13.0, npm 8.19.3

**What happened?**

The same issue from #504. Rewrites to `/api` are not working when using this package.

**What did you expect to happen?**

Rewrites to `/api` works

**Are you willing to submit a pull request to fix this bug?**

No

Reproduction URL: https://stackblitz.com/edit/github-hcetcs-b5hkgf?file=next.config.js

Reproduction:
1. Navigate to `/assets/image/og/test.png` in the right window on your screen
2. You will see `Error: socket hang up` meaning that NextJS tried to use `fallback` and rewrite you to example.com
3. Comment out the line `withNextTranslate(),`
4. Restart Next app from terminal and navigate to `/assets/image/og/test.png` again
5. You will see api route response `OK`l

**Comment by aralroca** [comment]
Thanks to the reproduction URL!

I think is related with this another old issue:  https://github.com/aralroca/next-translate/issues/822 using `next-compose-plugins` with `next-pwa`. I'm going to take a look for a solution!

**Comment by aralroca** [comment]
One thing I have seen that rewrites do not take into account locals. Without the next-translate library, with the i18n configuration of Next.js it doesn't work either.

```js
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});
const withPlugins = require('next-compose-plugins');
const withPWA = require('next-pwa');

const config = {
  i18n: {
    locales: ['en', 'de'],
    defaultLocale: 'en',
  },
  async rewrites() {
    return {
      beforeFiles: [
        {
          source: '/assets/image/og/:path*',
          destination: '/api/og?locale=en',
          has: [
            {
              type: 'host',
              value: 'localhost',
            },
          ],
        },
      ],
      fallback: [
        {
          source: '/api/:path*',
          destination: `http://example.com/api/:path*`,
        },
      ],
    };
  },
};

module.exports = withPlugins(
  [
    withPWA({
      pwa: {
        dest: 'public',
        disable: process.env.NODE_ENV === 'development',
      },
    }),
    withBundleAnalyzer,
  ],
  config
);

```

**Comment by abriginets** [comment]
@aralroca could you please create an issue at the origin repository of this issue? Please let me know if you do so, I will try to provide any context and configs I have.

**Comment by aralroca** [comment]
@abriginets the origin repository is [Next.js](https://github.com/vercel/next.js/) core. Here is all the documentation about i18n routing (all this part is from the core of Next.js not from the library): https://nextjs.org/docs/advanced-features/i18n-routing

Please add the issue in the Next.js repository if you consider that is an issue. Review the way of using the [`rewrite`](https://nextjs.org/docs/api-reference/next.config.js/rewrites), there are properties like `locale: false`, maybe this can solve your problem.
