### ISSUE TITLE
Support for Next13 appDir

### ISSUE THREAD

**Issue by mr0b0t0** [aralroca/next-translate#981]
Love next-translate! Are you planning to implement support for Next13 appDir?

**Comment by aralroca** [comment]
YES! and soon 😊 Today or tomorrow I'm going to do the PR about this part, it's almost ready, I only want to increase the number of tests

**Comment by mr0b0t0** [comment]
@aralroca, that is AMAZING! Thank you very much!!! ❤️ 🚀 🚀

**Comment by aralroca** [comment]
@mr0b0t0 You can already try it in [2.0.0-canary.3](https://github.com/aralroca/next-translate/releases/tag/2.0.0-canary.3. Please, if you can provide me with any feedback before the 2.0.0 release will be very welcome 😊

I wrote the documentation about how to use it inside the canary README.md, or also in the PR description.

**Comment by mr0b0t0** [comment]
Thank you! 😍 Going to try it ASAP

**Comment by mr0b0t0** [comment]
Working great so far! 💯 🚀  @aralroca

**Comment by aralroca** [comment]
> Working great so far! 💯 🚀 @aralroca

Nice to know it! Thanks! 😊👍 2.0.0 will be released soon
